### PR TITLE
[quest] Un'Goro quest fixes (Cata)

### LINKED ISSUE #6523: Quest 24715 Repairing A-Me 01 missing locations of item to collect
### Description

https://www.wowhead.com/cata/quest=24715/repairing-a-me-01

The quest requires you to collect one of these: https://www.wowhead.com/cata/object=201979/ungoro-coconut
These can be found here: `"{{61.2,20.9},{61.4,18.6},{61.9,17.2},{62.1,19.2},{62.5,22.5},},"`

Afterwards you have to go to an entity called "Sturdy Rock" and crack the coconut open to receive one of these: https://www.wowhead.com/cata/item=50236/high-viscosity-coconut-milk

Afterwards you can complete / hand in the quest.

### Questie version

v10.6.0

### Game flavor

Cata

### PR DESCRIPTION
**Pull request by coldpasta123**
## Issue references

Fixes #6523 

## Proposed changes

- [quest] Blacklist Zul Farrak quests removed with Cata
- [quest] Remove optional breadcrumb as required prequest for Claws of … …
- [quest] Mark Finding Stormclaw as optional breadcrumb
- [quest] Remove optional breadcrumbs as requirement for Volcanic Activity
- [quest] Mark Hero's Call: Un'Goro Crater! as optional breadcrumb
- [quest] Mark Warchief's Command: Un'Goro Crater! as optional breadcrumb
- Change exclusive to nextquest
- [quest] Mark Tropical Paradise Beckons as optional breadcrumb
- [quest] Improve objective for Finding the Source
- [db] Fix objective location for Finding the Source
- [quest] Improve objectives for Town Dwellers Were Made to be Saved
- [db] Rename damsels to dwellers
- [quest] Add objectives for The Spirits of Golakka Hot Springs
- [quest] Improve objective for The Ballad of Maximillian
- [db] Fix drop locations for Preserved Pheromone Mixture
- [db] Fix drop for Preserved Threshadon Meat
- [quest] Add objective for How to Make Meat Fresh Again
- [quest] Add prequest for The Fledgling Colossus
- [db] Add patrol path for Durrin Direshovel
- Fix waypoints
- [quest] QIB for Repairing A-Me 01
- [db] Add patrol path for Gormashh
- [quest] Fix prequests for The Shaper's Terrace
- [quest] Improve objectives for The Shaper's Terrace
- Translation for The Shaper's Terrace
- [quest] Improve objectives for Ever Watching From Above
- Translation for Ever Watching From Above
- [quest] Blacklist Un'Goro quests removed with Cata
- [quest] Blacklist Dadanga is Hungry!
- [quest] Blacklist old Pylon quests
- [db] Fix locations for Red Power Crystal
- [db] Fix locations for Blue Power Crystal
- [db] Fix locations for Green Power Crystal
- [db] Fix locations for Yellow Power Crystal

### CODE REVIEW

File: Database/Corrections/cataQuestFixes.lua [hunk 1]
```diff
@@ -3116,6 +3116,7 @@ function CataQuestFixes.Load()
         },
         [24707] = { -- The Ballad of Maximillian
             [questKeys.preQuestSingle] = {24706},
+            [questKeys.objectives] = {{{38708,nil,Questie.ICON_TYPE_EVENT}}}
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:3129]: Why do we need an event icon for this? The quest seems to ask the player to kill [the queen](https://www.wowhead.com/cata/npc=38708/devilsaur-queen)

File: Database/Corrections/cataQuestFixes.lua [hunk 2]
```diff
@@ -3083,8 +3083,18 @@ function CataQuestFixes.Load()
...
         [24694] = { -- The Shaper's Terrace
-            [questKeys.preQuestSingle] = {24723},
+            [questKeys.preQuestGroup] = {24720,24721,24722,24723},
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Talk to the Un'Goro Examinant"),0,{{"monster",38504}}}},
+        },
+        [24695] = { -- Ever Watching From Above
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202187}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202195}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202196}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202197}}}},
+        },
+        [24697] = { -- How to Make Meat Fresh Again
+            [questKeys.objectives] = {{{9163,nil,Questie.ICON_TYPE_EVENT}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:3097]: Since you need to use items on specific NPCs I prefer the interact icon

```suggestion
            [questKeys.objectives] = {{{9163,nil,Questie.ICON_TYPE_INTERACT}}},
```

File: Database/Corrections/cataQuestFixes.lua [hunk 3]
```diff
@@ -3083,8 +3083,18 @@ function CataQuestFixes.Load()
...
+            [questKeys.preQuestSingle] = {24690},
+        },
         [24694] = { -- The Shaper's Terrace
-            [questKeys.preQuestSingle] = {24723},
+            [questKeys.preQuestGroup] = {24720,24721,24722,24723},
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Talk to the Un'Goro Examinant"),0,{{"monster",38504}}}},
+        },
+        [24695] = { -- Ever Watching From Above
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202187}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202195}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202196}}},{nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202197}}}},
+        },
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:3095]: This is just formatting

```suggestion
            [questKeys.extraObjectives] = {
                {nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202187}}},
                {nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202195}}},
                {nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202196}}},
                {nil,Questie.ICON_TYPE_INTERACT,l10n("Pull the lever"),0,{{"object",202197}}}
            },
        },
```

File: Database/Corrections/cataQuestFixes.lua (hunk 1 above)
Comment (coldpasta123) [reply Database/Corrections/cataQuestFixes.lua]: @BreakBB good point - I have changed to an extraObjective to start the event https://github.com/Questie/Questie/pull/6658/commits/3dbf1990bb206d03726082e8dd10015ac5924668

Comment (Cabro) [reply Database/Corrections/cataQuestFixes.lua]: Oh, Maximillian is a naughty NPC. Did you fix coords for it for every location?

Comment (coldpasta123) [reply Database/Corrections/cataQuestFixes.lua]: He has a static point but can also follow you around - how would you fix coords for that?

Comment (Cabro) [reply Database/Corrections/cataQuestFixes.lua]: i'd just add spawns to each spot where he's supposed to be near you for the said quests. i guess we need some phase spawns for this, i'll do when i get to that zone

Comment (coldpasta123) [reply Database/Corrections/cataQuestFixes.lua]: @BreakBB going to resolve this for now - phasing idea is sensible but I don't know how to do it, and it's not a blocker for any of these other changes
