### PR TITLE
[quest] ADDED: 'Trial of The Owls' Rune Quest To QuestDB

### LINKED ISSUE #5377: [quest]: 'Trial of The Owls' Missing From QuestDB
## Description

The SoD quest 'Trial of The Owls' is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/quest=78229/trial-of-the-owls

### Discord Bug Report

Quest ID: 78229
Quest Name: Trial of The Owls
Quest Text: 
Objective Text: 
Reward Text: I would like to congratulate you, <playername>. What you've accomplished is no small feat.

To pass the trial of the owls is to demonstrate an attunement with all aspects of your druidic calling.
 
Take this rune as a mark of your achievement. I hope it will serve you well as a warden of the Emerald Dream.
Reward XP: 2000
Questgiver: Creature-0-5176-1-21098-12042-00000D9968
Character: Lvl 24 NIGHTELF DRUID
Player Coords:  [1450]  (52.468, 40.463)
QuestLog: 78229, 199, 344, 1011, 8372, 271, 

## Screenshots

N/a

## Questie & WoW version

v9.2.10
WoW Classic SoD - v1.15.052409

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #5377

## Proposed changes

- ADDED: 'Trial of The Owls' is now in the QuestDB, and should be accessible to users.

### CODE REVIEW

**Comment by Sommos** [comment]
The quest can only be picked up once the player has ONE of the three owl symbols required as per the comment left by 'kohuh' on the WoWHead page here: https://www.wowhead.com/classic/quest=78229/trial-of-the-owls

How would we put this functionality in?

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 1]
```diff
@@ -493,6 +493,17 @@ function SeasonOfDiscovery:LoadBaseQuests()
             [questKeys.objectivesText] = {"Travel to the Echo Isles and use the offering at Bwonsamdi's shrine."},
             [questKeys.objectives] = nil,
         },
+        [78229] = {
+            [questKeys.name] = "Trial of The Owls",
+            [questKeys.startedBy] = {{12042}},
+            [questKeys.finishedBy] = nil,
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:499]:
```suggestion
            [questKeys.finishedBy] = {{12042,}},
```

**Review by BreakBB — COMMENTED** [review]
No, there is no way to add such logic atm.

I suggest you create three fake rune quests for the actual owl locations and edit the objective text of the main quest to explain that you need at least one of the owls to accept the quest.

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 2]
```diff
@@ -493,15 +493,48 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+            [questKeys.name] = "Trial of The Owls",
+            [questKeys.startedBy] = nil,
+            [questKeys.finishedBy] = {{12042,}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.objectivesText] = {"Obtain 1 symbol of the owl to start the Trial of The Owls quest chain."},
+            [questKeys.objectives] = {nil,nil,{{210044}}},
+        },
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:528]: First of all: No manual edits in the base file!

Moreover you should not use these IDs, because they are in the "valid quest ID" range and Blizzard might decide to use them for actual quests in the future. Instead you should move these entirely into the questFixes file. At the bottom of the corrections there you'll fine a "fake quests" section, starting with ID 90000.

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 3]
```diff
@@ -493,15 +493,48 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
             [questKeys.name] = "Trial of The Owls",
             [questKeys.startedBy] = {{12042}},
-            [questKeys.finishedBy] = nil,
+            [questKeys.finishedBy] = {{12042,}},
             [questKeys.requiredLevel] = 1,
             [questKeys.questLevel] = 25,
             [questKeys.requiredRaces] = raceIDs.NONE,
             [questKeys.requiredClasses] = classIDs.DRUID,
-            [questKeys.objectivesText] = {"Bring symbols of the three owls to Loganaar in Moonglade."},
+            [questKeys.objectivesText] = {"To start this quest, bring 1 symbol of the owl to Loganaar in Moonglade."},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:537]: No manual edits in the base file, move this correction to the questFixes file.

**Review by BreakBB — COMMENTED** [review]
- The fake quests you added also have no `startedBy` and will therefore not show up anywhere
   - **First Trial**: I am unsure which game object should be used as `startedBy`. It is one of the "Owl statues". If you have a Druid it would be great if you could run to [this location](https://www.wowhead.com/classic/npc=211269/summoned-wisp) and check if you find out the object ID. Maybe some other Druid can help you as well
   - **Second Trial**: Not sure either which game object should be used to get the buff to see Agon
   - **Third Trial**: Add the correct spawns to [this object](https://www.wowhead.com/classic/object=409949/twin-owl-statue) which serves as the one to get the swimming buff. But most likely we need more objects to show the ones you need to click while swimming.
- The `objectiveText` should explain how to start the trial
- Since these are fake quests they do not need `objectives` (objectives are only required for quests which can be in the quest log of a player)
- The fake quests also need a `requiredSpell` field to hide them once the player learned the rune

File: Database/Corrections/Automatic/sodBaseQuests.lua (hunk 3 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseQuests.lua]: I really need to get it through my head that we don't touch the base files in anyway outside of adding direct scraper data. xD

Fixed in : https://github.com/Questie/Questie/pull/5378/commits/a85ba7acb03f879941f032824afdf66ff09c1434

File: Database/Corrections/sodQuestFixes.lua [hunk 4]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
             [questKeys.requiredSpell] = -400099,
             [questKeys.zoneOrSort] = sortKeys.ROGUE,
         },
+        [90088] = {
+            [questKeys.name] = "First Trial of The Owls",
+            [questKeys.startedBy] = {{210044}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1684]:
```suggestion
            [questKeys.startedBy] = {nil,{410020}},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 5]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
...
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.requiredSpell] = -410028,
+            [questKeys.objectivesText] = {"Click the owl statue to collect 1 symbol of the owl to start the Trial of The Owls quest chain."},
+            [questKeys.zoneOrSort] = sortKeys.DRUID,
+        },
+        [90089] = {
+            [questKeys.name] = "Second Trial of The Owls",
+            [questKeys.startedBy] = {{210043}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1696]:
```suggestion
            [questKeys.startedBy] = {nil,{410089}},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 6]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
...
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.requiredSpell] = -410028,
+            [questKeys.objectivesText] = {"Click the owl statue to see Agon, kill him and collect 1 symbol of the owl to start the Trial of The Owls quest chain."},
+            [questKeys.zoneOrSort] = sortKeys.DRUID,
+        },
+        [90090] = {
+            [questKeys.name] = "Third Trial of The Owls",
+            [questKeys.startedBy] = {{210026}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1708]:
```suggestion
            [questKeys.startedBy] = {nil,{409942,409949}},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 7]
```diff
@@ -245,6 +245,11 @@ function SeasonOfDiscovery:LoadQuests()
             [questKeys.finishedBy] = {nil,{410168}},
             [questKeys.requiredRaces] = raceIDs.UNDEAD,
         },
+        [78229] = {
+            [questKeys.preQuestGroup] = {90088,90089,90090},
+            [questKeys.zoneOrSort] = sortKeys.DRUID,
+            [questKeys.objectivesText] = {"To start this quest, bring 1 symbol of the owl to Loganaar in Moonglade. You need to bring at least 1 symbol, but you can bring all three at once."},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:251]:
```suggestion
            [questKeys.objectivesText] = {"Bring symbols of the three owls to Loganaar in Moonglade. NOTE: To accept this quest, you need to bring at least one symbol, but you can also bring all three at once."},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 8]
```diff
@@ -245,6 +245,11 @@ function SeasonOfDiscovery:LoadQuests()
             [questKeys.finishedBy] = {nil,{410168}},
             [questKeys.requiredRaces] = raceIDs.UNDEAD,
         },
+        [78229] = {
+            [questKeys.preQuestGroup] = {90088,90089,90090},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:249]: This is a nice idea, but doesn't make any difference since the fake quests are never in the quest log or marked as "complete".

We can leave it in though, as we might add logic for this at some point 🤷🏻

File: Database/Corrections/sodQuestFixes.lua [hunk 9]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
...
+        [90088] = {
+            [questKeys.name] = "First Trial of The Owls",
+            [questKeys.startedBy] = {{210044}},
+            [questKeys.finishedBy] = {{12042}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.requiredSpell] = -410028,
+            [questKeys.objectivesText] = {"Click the owl statue to collect 1 symbol of the owl to start the Trial of The Owls quest chain."},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1691]:
```suggestion
            [questKeys.objectivesText] = {"Click the Owl Statue to start the the first trial. If you succeed you'll receive the Symbol of the First Owl."},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 10]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
...
+        [90089] = {
+            [questKeys.name] = "Second Trial of The Owls",
+            [questKeys.startedBy] = {{210043}},
+            [questKeys.finishedBy] = {{12042}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.requiredSpell] = -410028,
+            [questKeys.objectivesText] = {"Click the owl statue to see Agon, kill him and collect 1 symbol of the owl to start the Trial of The Owls quest chain."},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1703]:
```suggestion
            [questKeys.objectivesText] = {"Click the Owl Statue to become able to see Agon. Defeat him and collect the Symbol of the Second Owl."},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 11]
```diff
@@ -1674,6 +1679,42 @@ function SeasonOfDiscovery:LoadQuests()
...
+        [90090] = {
+            [questKeys.name] = "Third Trial of The Owls",
+            [questKeys.startedBy] = {{210026}},
+            [questKeys.finishedBy] = {{12042}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 25,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.DRUID,
+            [questKeys.requiredSpell] = -410028,
+            [questKeys.objectivesText] = {"Click 1 symbol of the owl to start, and click the other in 2 minutes. You may need to use aquatic form."},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:1715]:
```suggestion
            [questKeys.objectivesText] = {"Click one of the Twin Owl Statues and reach the other in two minutes. You need to use Aquatic Form to make it in time. If you succeed you'll receive the Symbol of the Third Owl."},
```

File: Database/Corrections/sodItemFixes.lua [hunk 12]
```diff
@@ -35,6 +35,16 @@ function SeasonOfDiscovery:LoadItems()
         [209846] = {
             [itemKeys.objectDrops] = {409692},
         },
+        [210026] = {
+            [itemKeys.objectDrops] = {409942,409949},
+        },
+        [210043] = {
+            [itemKeys.objectDrops] = {410089},
```
Comment (BreakBB) [inline Database/Corrections/sodItemFixes.lua:42]: The item is only dropped by Agon. The quests will though nevertheless.

```suggestion
```

File: Database/Corrections/sodQuestFixes.lua (hunk 8 above)
Comment (Sommos) [reply Database/Corrections/sodQuestFixes.lua:249]: I'll leave it in there for the moment in the case that we will need it later. Can remove it in the next sub-major release if it still is not used.

File: Database/Corrections/sodQuestFixes.lua (hunk 7 above)
Comment (Sommos) [reply Database/Corrections/sodQuestFixes.lua]: Fixed in: https://github.com/Questie/Questie/pull/5378/commits/8485acaea2c00c71ca578d6e7e88c89694e5daef

File: Database/Corrections/sodQuestFixes.lua (hunk 4 above)
Comment (Sommos) [reply Database/Corrections/sodQuestFixes.lua]: Fixed in: https://github.com/Questie/Questie/pull/5378/commits/bfe0509185f2ffde9c120eac643cc22f9e92d074

File: Database/Corrections/sodItemFixes.lua (hunk 12 above)
Comment (Sommos) [reply Database/Corrections/sodItemFixes.lua:42]: Should we then remove the entire entry instead of just the attribute?

Comment (BreakBB) [reply Database/Corrections/sodItemFixes.lua:42]: Yeah, we don't need this correction, as the base file already contains the correct `npcDrops` 👍🏻

Comment (Sommos) [reply Database/Corrections/sodItemFixes.lua]: Fixed in: https://github.com/Questie/Questie/pull/5378/commits/0e47e97e020e00ce5abc0d0ebf34567c00787661

**Review by BreakBB — APPROVED** [review]
