### PR TITLE
[quest] Ashenvale quest fixes (Cata)

### LINKED ISSUE #6230: Quest Issue - Dread Head Redemption (Cata Classic)
## Description

No marker on map for quest drop

## Wowhead link

Quest: https://www.wowhead.com/cata/quest=13842/dread-head-redemption
Quest item: https://www.wowhead.com/cata/item=60638/duraks-head
Quest item drops from: https://www.wowhead.com/cata/npc=44414/durak

## Questie & WoW version

Cata Classic
Questie 10.3.3

### LINKED ISSUE #6231: Quest Issue - Shrouded in Nightmare (Cata Classic)
## Description

Shrouded in Nightmare quest no longer available in Cata Classic

## Wowhead link

https://www.wowhead.com/cata/quest=8446/shrouded-in-nightmare

## Questie & WoW version

Cata Classic
Questie 10.3.3

### LINKED ISSUE #6232: Quest Issue - Shadumbra's Head (Cata Classic)
## Description

Patrol path for Shadumbra has changed in Cata Classic to extend up north of Raynewood retreat. Map patrol line needs updating (see pic attached).

## Wowhead link

https://www.wowhead.com/cata/npc=12677/shadumbra

## Screenshots

image

## Questie & WoW version

Cata Classic
Questie 10.3.3

### LINKED ISSUE #6236: Quest Issue - Vortex (Cata Classic)
## Description

The quest Vortex is showing as available before it is actually available. It requires both of the following to be completed first:

- Put Out The Fire (https://www.wowhead.com/cata/quest=13884/put-out-the-fire) 
- Hot Lava (https://www.wowhead.com/cata/quest=13880/hot-lava)

## Wowhead link

https://www.wowhead.com/cata/quest=13888/vortex

## Questie & WoW version

Cata Classic
Questie 10.3.7

### LINKED ISSUE #6357: Quest Issue - Splintertree Post prequests (Cata - Ashenvale)
## Description

Splintertree quests missing prequests - TBC

## Wowhead link

https://www.wowhead.com/cata/quest=13730/playing-with-felfire (prequest Blood of the Weak)
https://www.wowhead.com/cata/quest=13841/all-apologies (prequest Rain of Destruction)
https://www.wowhead.com/cata/quest=13806/demon-duty (prequest Never Again)
https://www.wowhead.com/cata/quest=13801/dead-elves-walking (prequest Blood of the Weak)
https://www.wowhead.com/cata/quest=6441/satyr-horns (prequest Never Again)
https://www.wowhead.com/cata/quest=13808/mission-improbable (prequest Pierce Their Heart)
https://www.wowhead.com/cata/quest=13848/bad-news-bear-er (prequest Pierce Their Heart)
https://www.wowhead.com/cata/quest=13870/as-good-as-it-gets (prequests Wet Work and Making Stumps)

## Questie & WoW version

Cata
10.3.11

### LINKED ISSUE #6358: [Quest Issue] Rain of Destruction (Cata)
## Description

No quest objective markers

## Wowhead link

https://www.wowhead.com/cata/quest=13798/rain-of-destruction

## Questie & WoW version

Cata
10.3.11

### LINKED ISSUE #6361: Quest Issue - Diabolical Plans (Cata - Ashenvale)
## Description

Not showing as available (triggered by item drop)

## Wowhead link

https://www.wowhead.com/cata/quest=26447/diabolical-plans

## Questie & WoW version

Cata
Questie 10.3.12

### PR DESCRIPTION
**Pull request by coldpasta123**
## Issue references

Fixes #6357
Fixes #6358 
Fixes #6232 
Fixes #6231 
Fixes #6230 
Fixes #6236 
Fixes #6361 

## Proposed changes

- Fix prequests for Splintertree Post quest lines
- Add objectives for Rain of Destruction
- Blacklist Shrouded in Nightmare (removed in Cata)
- Update Shadumbra patrol route for Cata
- Fix objectives for Dread Head Redemption
- Fix prequests for Vortex
- Fix Diabolical Plans (started by item drop)

### CODE REVIEW

File: Database/Corrections/cataQuestFixes.lua [hunk 1]
```diff
@@ -1142,6 +1145,7 @@ function CataQuestFixes.Load()
             [questKeys.nextQuestInChain] = 26465,
         },
         [13621] = { -- Gorat's Vengeance
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_INTERACT,l10n("Use the imbued blood"),0,{{"monster",33294}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1148]: If you add any new string that is used in `l10n(...)` then that also needs to be added to this list:

https://github.com/Questie/Questie/blob/master/Localization/Translations/ExtraObjectives/CataObjectives.lua

File: Database/Corrections/cataQuestFixes.lua [hunk 2]
```diff
@@ -1156,6 +1160,9 @@ function CataQuestFixes.Load()
         [13646] = { -- Astranaar Bound
             [questKeys.preQuestSingle] = {26464},
         },
+        [13653] = { -- Crisis at Splintertree
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Speak to Gorka"),0,{{"monster",33421}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1164]: Same as above with `l10n(...)`. On top it kind of looks like the `objectives` of this quest is a bunny NPC. I'd say that the objectives can be cleared and instead a `triggerEnd` can be added with the location of where the quest will be complete. That way users can at least see where the quests will be done.

File: Database/Corrections/cataQuestFixes.lua [hunk 3]
```diff
@@ -1214,26 +1221,50 @@ function CataQuestFixes.Load()
         [13708] = { -- Valiant Of Sen'jin
             [questKeys.requiredRaces] = raceKeys.ALL_HORDE,
         },
+        [13712] = { -- To The Rescue
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Speak to Kadrak"),0,{{"monster",8582}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1225]: Same as above: new string that needs to be added to the translations and also `triggerEnd` instead of `objectives`.

File: Database/Corrections/cataQuestFixes.lua [hunk 4]
```diff
@@ -1214,26 +1221,50 @@ function CataQuestFixes.Load()
...
+        },
         [13766] = { -- Closure is Only Natural
             [questKeys.objectives] = {{{33767,nil,Questie.ICON_TYPE_EVENT}}},
         },
         [13796] = { -- The Forest Heart
             [questKeys.preQuestSingle] = {13792},
             [questKeys.requiredSourceItems] = {45571,45572},
         },
+        [13798] = { -- Rain of Destruction
+            [questKeys.objectives] = {{{33688}},nil,nil,nil,{{{33945,33195},33195,"Attacking elves slain"}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1238]: For this quest you need to add something else. By default Questie will match the objectives the API returns in order with the objectives. That would mean that the `monster` objective would be taken as "Attacking Elves Slain" and the `killCreditObjective` would be for the Ancients.

To fix this order mismatch, at the top of this file you need to add `QuestieCorrections.killCreditObjectiveFirst[13798] = true` (there are other entries already).

File: Database/Corrections/cataQuestFixes.lua [hunk 5]
```diff
@@ -1214,26 +1221,50 @@ function CataQuestFixes.Load()
...
             [questKeys.requiredRaces] = raceKeys.ALL_ALLIANCE,
             [questKeys.preQuestSingle] = {13528},
         },
         [13841] = { -- All Apologies
+            [questKeys.preQuestSingle] = {13798},
             [questKeys.finishedBy] = {{39605}},
         },
         [13842] = { -- Dread Head Redemption
             [questKeys.finishedBy] = {{39605}},
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Soeak to Durek"),0,{{"monster",44414}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1259]:
```suggestion
            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_TALK,l10n("Speak to Durek"),0,{{"monster",44414}}}},
```

Also that string needs to be added to the translations.

File: Database/Corrections/cataQuestFixes.lua [hunk 6]
```diff
@@ -4409,11 +4447,6 @@ function CataQuestFixes.Load()
         [26434] = { -- Primal Reagents of Power
             [questKeys.preQuestSingle] = {26433},
         },
-        [26440] = { -- Clingy
-            [questKeys.triggerEnd] = {"Pebble brought to crystal formation",{[zoneIDs.DEEPHOLM]={{29.45,47.47}}}},
-            [questKeys.objectives] = {},
-            [questKeys.preQuestSingle] = {26439},
-        },
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:4416]: Good catch, thanks for cleaning up the order here 👍🏻

**Review by BreakBB — CHANGES_REQUESTED** [review]

**Review by coldpasta123 — COMMENTED** [review]
@BreakBB can you check I've done this right please (just did one as an example; I know there are more changes required);

**Comment by BreakBB** [comment]
Hey @coldpasta123 yeah that is correct for the one quest 👍🏻

File: Database/Corrections/cataQuestFixes.lua (hunk 2 above)
Comment (coldpasta123) [reply Database/Corrections/cataQuestFixes.lua:1182]: https://github.com/Questie/Questie/pull/6359/commits/aabb11e3716d0fa09366997b071585d49b673920

@Cabro I asked you about this on discord a few days ago - would you mind checking I've done correctly please?

File: Database/Corrections/cataQuestFixes.lua [hunk 7]
```diff
@@ -4454,9 +4489,17 @@ function CataQuestFixes.Load()
...
+            [questKeys.triggerEnd] = {"Pebble brought to crystal formation",{[zoneIDs.DEEPHOLM]={{29.45,47.47}}}},
+            [questKeys.objectives] = {},
+            [questKeys.preQuestSingle] = {26439},
+        },
         [26442] = { -- Rock Lobster
             [questKeys.exclusiveTo] = {29325,29321,29323,29324,29342,29343,29344,29347,29350,29359,26414,26420,26488,26536},
         },
+        [26447] = { -- Diabolical Plans
+            [questKeys.startedBy] = {nil,nil,{23798}},
+        },
```
Comment (Cabro) [inline Database/Corrections/cataQuestFixes.lua:4502]: What did you want to do with this one here? :)

File: Database/Corrections/cataQuestFixes.lua (hunk 2 above)
Comment (Cabro) [reply Database/Corrections/cataQuestFixes.lua:1182]: Looks good

File: Database/Corrections/cataQuestFixes.lua (hunk 7 above)
Comment (coldpasta123) [reply Database/Corrections/cataQuestFixes.lua:4502]: Add a marker similar to that for the Ashenvale hunt quests (e.g. Shadumbra)
