### PR TITLE
[fix] Show Tracker even without any quest tracked

### LINKED ISSUE #3315: Show tracker header even 0 quests are tracked.
Show tracker header even 0 quests are tracked.

### PR DESCRIPTION
**Pull request by BreakBB**
Fixes #3315

### CODE REVIEW

File: Modules/Tracker/QuestieTracker.lua [hunk 1]
```diff
@@ -1826,7 +1822,11 @@ function QuestieTracker:Update()
         end)
     end
 
-    if hasQuest and _QuestieTracker.IsFirstRun == nil then
+    if (not hasQuest) then
+        QuestieTracker:Collapse()
+    end
```
Comment (BreakBB) [inline Modules/Tracker/QuestieTracker.lua:1827]:
```suggestion
```
