### PR TITLE
[quest] Fix 'Horn of Nez'ra' Unavailable In Cata

### LINKED ISSUE #6069: WoW Classic - Quest 2358 unavailable quest shows up on map
The quest https://www.wowhead.com/cata/de/quest=2358/h%C3%B6rner-von-nezra shows up on WoW Classic server on the map/minimap with a quest icon, but isn't available at the NPC:
image

### LINKED ISSUE #6159: Quest Issue for quest 14365 - Ethel Rethor (Desolace, Cataclysm Classic)
## Description
Alliance quest shows up on map minimap prematurely, requires a prerequisite quest to be completed first

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=14365/ethel-rethor
Prerequisite: https://www.wowhead.com/cata/quest=14354/elunes-gifts

## Questie & WoW version
Questie 10.3.5 & Cataclysm Classic

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #6069

## Proposed changes

- Add a fix to Questie corrections for the 'Horn of  Nez'ra' quest to blacklist it in Cata.

### CODE REVIEW

File: Database/Corrections/QuestieQuestBlacklist.lua [hunk 1]
```diff
@@ -9,7 +9,7 @@ function QuestieQuestBlacklist:Load()
         [7462] = true, -- Duplicate of 7877. See #1583
         [5663] = true, -- Touch of Weakness of Dark Cleric Beryl - Fixing #730
         [5658] = true, -- Touch of Weakness of Father Lankester -- See #1603
-        [2358] = QuestieCorrections.CLASSIC_HIDE + QuestieCorrections.SOD_HIDE + QuestieCorrections.TBC_HIDE, -- See #921
+        [2358] = QuestieCorrections.CLASSIC_HIDE + QuestieCorrections.SOD_HIDE + QuestieCorrections.TBC_HIDE + QuestieCorrections.CATA_HIDE, -- See #921
```
Comment (BreakBB) [inline Database/Corrections/QuestieQuestBlacklist.lua:12]:
```suggestion
        [2358] = true, -- See #921
```
