### PR TITLE
[quest] ADDED: 'Venture Co. Work Order' & 'The Horn of Xelthos' Quests To QuestDB

### LINKED ISSUE #5337: [quest]: 'Goblin Lockpicks' Missing From QuestDB
## Description

The SoD quest 'Goblin Lockpicks' is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/quest=78270/goblin-lockpicks

### Discord Bug Report

Quest ID: 78270
Quest Name: Goblin Lockpicks
Quest Text: <A note sits in the chest> Hello again, <name>. I desire a treasure known as The Horn of Xelthos, which is somewhere within Shadowfang Keep. Venturing inside the keep usually calls for backup. However, for this job, a low profile is of utmost importance. You must go alone. I have a contact, by the name of Veenix, in the Stonetalon Mountains. He should be able to help you get past the courtyard gate. The rest is up to you. Return the horn here, and your payment will be sent soon after. - C

Objective Text: Find The Horn of Xelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village.
Reward Text: Nice job, <playername>. I figure that was a cakewalk for someone in your line of work.

As promised, here's the goods.
Reward XP: 0
Questgiver: Creature-0-5175-1-4352-4086-0000020165
Character: Lvl 21 ORC ROGUE
Player Coords:  [1442]  (58.259, 51.692)
QuestLog: 1486, 896, 877, 1858, 78261, 235, 2479, 6562, 1068, 6542, 962, 1487, 821, 867, 959, 850, 865, 7024, 
Client: 1.15.0 SoD
Questie: v9.2.9
Locale: enUS

## Screenshots

N/a

## Questie & WoW version

v9.2.9
WoW Classic SoD - v1.15.052409

### LINKED ISSUE #5365: [quest]: 'The Horn of Xelthos' Missing From QuestDB
## Description

The SoD quest 'The Horn of Xelthos' is not currently in the QuestDB. 

## Wowhead link

https://www.wowhead.com/classic/quest=78261/the-horn-of-xelthos

### Discord Bug Report

Quest ID: 78261
Quest Name: The Horn of Xelthos
Quest Text: <A note sits in the chest>

Hello, <playername>.

I desire a treasure known as The Horn of Xelthos, which is somewhere within Shadowfang Keep.

Venturing inside the keep usually calls for backup. However, for this job, a low profile is of utmost importance.

You must go alone.

I have a contact, by the name of Veenix, in the Stonetalon Mountains. He should be able to help you get past the courtyard gate. The rest is up to you. 

Return the horn here, and your payment will be sent soon after.

C
Objective Text: Find The Horn of Xelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village. You must complete the job alone.
Character: Lvl 22 SCOURGE ROGUE
Player Coords:  [1421]  (45.030, 41.839)
QuestLog: 1098, 235, 1069, 5725, 893, 868, 896, 1014, 1130, 1491, 78261, 1483, 6543, 3924, 878, 
Client: 1.15.0 SoD
Questie: v9.2.9
Locale: enUS

## Screenshots

N/a

## Questie & WoW version

v9.2.9
WoW Classic SoD - v1.15.052409

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #5337 
Fixes #5365

## Proposed changes

- ADDED:  'Venture Co. Work Order' is now in the QuestDB, and should be accessible to users.
- ADDED:  'The Horn of Xelthos' is now in the QuestDB, and should be accessible to users.

### CODE REVIEW

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 1]
```diff
@@ -399,6 +399,17 @@ function SeasonOfDiscovery:LoadBaseQuests()
             [questKeys.requiredRaces] = raceIDs.NONE,
             [questKeys.requiredClasses] = classIDs.NONE,
         },
+        [78270] = {
+            [questKeys.name] = "Goblin Lockpicks",
+            [questKeys.startedBy] = {{210187}},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:404]: The first entry of the `startedBy` table is a table of NPC IDs which start a quest. This can either be friendly/neutral NPCs to which the player has to talk or hostile NPCs from which the player has to loot an item, which starts the quest.

In this case you want it to be the NPCs which "drop" the `Venture Co. Work Order`.

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 2]
```diff
@@ -399,6 +399,17 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+            [questKeys.finishedBy] = {{4086}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 23,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.NONE,
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:409]:
```suggestion
            [questKeys.requiredClasses] = classIDs.ROGUE,
```

File: Database/Corrections/Automatic/sodBaseItems.lua [hunk 3]
```diff
@@ -2827,7 +2827,7 @@ function SeasonOfDiscovery:LoadBaseItems()
             [itemKeys.objectDrops] = nil,
             [itemKeys.itemDrops] = nil,
             [itemKeys.vendors] = nil,
-            [itemKeys.startQuest] = nil,
+            [itemKeys.startQuest] = {78270},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseItems.lua:2830]: We don't want to manually edit the `sodBase<X>.lua` files, because we generate them using the scraper and do a full replacement when re-scraping.

Manual overrides should go to the `sod<X>Fixes.lua` - `sodItemFixes.lua` in this case.

**Review by BreakBB — CHANGES_REQUESTED** [review]
Since this quest is also related to the [Rune of Deadly Brew](https://www.wowhead.com/classic/item=203994/rune-of-deadly-brew) you want to mark it is a rune quest in the `SeasonOfDiscovery.lua` file.

Moreover I am quite sure the map will be flooded with "Accept" icons if you add the correct NPCs dropping "Venture Co. Work Order". So hide it for now, just like we do with other similar rune quests, also in the `SeasonOfDiscovery.lua` file.

File: Database/Corrections/Automatic/sodBaseQuests.lua (hunk 1 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseQuests.lua]: Fixed in: https://github.com/Questie/Questie/pull/5339/commits/3197ef226acfa58c0d5e76bd3c75d0cb3cb9fd5f

File: Database/Corrections/Automatic/sodBaseQuests.lua (hunk 2 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseQuests.lua]: Yeah, last night the scraper and WoWHead had barely any information on it, and didn't include that it was a Rogue quest.

Fixed in: https://github.com/Questie/Questie/pull/5339/commits/3197ef226acfa58c0d5e76bd3c75d0cb3cb9fd5f

Added in the `zoneOrSort` in `sodQuestFixes.lua` here: https://github.com/Questie/Questie/pull/5339/commits/2b8bf89b8d9637a47ab351d5eb1809d9f6728214

File: Database/Corrections/Automatic/sodBaseItems.lua (hunk 3 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseItems.lua]: Okay. I need to go and take another look at the scraper stuff then. So we should avoid doing anything to `sodBaseQuests.lua` as well, and should just be put in to the corresponding `sod<X>Fixes.lua` (`sodQuestFixes.lua` in this case) file?

Fixed in: https://github.com/Questie/Questie/pull/5339/commits/8c03e4eada7c08ed1ad57770512b7205eddf4164

Comment (BreakBB) [reply Database/Corrections/Automatic/sodBaseItems.lua]: In the base files we don't want to do specific fixes for certain quests/fields, because they might get removed/replaced in a later scrape. For the `sodBaseQuests.lua` file in specific we want to add scraped quests one step at a time, to verify they come in with the required fixes. The other base files have already been replaced entirely multiple times.

Therefore manual overrides should go to the corresponding Fixes file.

File: Database/Corrections/Automatic/sodBaseItems.lua [hunk 4]
```diff
@@ -2821,14 +2821,6 @@ function SeasonOfDiscovery:LoadBaseItems()
...
             [itemKeys.startQuest] = nil,
         },
-        [210187] = {
-            [itemKeys.name] = "Venture Co. Work Order",
-            [itemKeys.npcDrops] = {3988,4070,3992,3993},
-            [itemKeys.objectDrops] = nil,
-            [itemKeys.itemDrops] = nil,
-            [itemKeys.vendors] = nil,
-            [itemKeys.startQuest] = nil,
-        },
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseItems.lua:2831]: We want to keep the entry. Just never edit any of the `sodBase` files with the exception of the `sodBaseQuests.lua` file for when you add a new quest from the scraper.

When scraping the latest wowhead state for SoD, we replace the entire base files to mirror that state.

File: Database/Corrections/sodItemFixes.lua [hunk 5]
```diff
@@ -32,6 +32,14 @@ function SeasonOfDiscovery:LoadItems()
         [209846] = {
             [itemKeys.objectDrops] = {409692},
         },
+        [210187] = {
+            [itemKeys.name] = "Venture Co. Work Order",
+            [itemKeys.npcDrops] = {3988,4070,3992,3993},
+            [itemKeys.objectDrops] = nil,
+            [itemKeys.itemDrops] = nil,
+            [itemKeys.vendors] = nil,
+            [itemKeys.startQuest] = {78270},
```
Comment (BreakBB) [inline Database/Corrections/sodItemFixes.lua:41]: Only keep this override in there and move the rest back to the base file

Comment (Sommos) [reply Database/Corrections/sodItemFixes.lua:39]: Fixed in: https://github.com/Questie/Questie/pull/5339/commits/2d618139cf5b19c5a1926c230a55a5dd9dd0360c

File: Database/Corrections/Automatic/sodBaseItems.lua (hunk 4 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseItems.lua]: Fixed in: https://github.com/Questie/Questie/pull/5339/commits/2d618139cf5b19c5a1926c230a55a5dd9dd0360c

File: Database/Corrections/Automatic/sodBaseItems.lua [hunk 6]
```diff
@@ -2824,10 +2824,6 @@ function SeasonOfDiscovery:LoadBaseItems()
         [210187] = {
             [itemKeys.name] = "Venture Co. Work Order",
             [itemKeys.npcDrops] = {3988,4070,3992,3993},
-            [itemKeys.objectDrops] = nil,
-            [itemKeys.itemDrops] = nil,
-            [itemKeys.vendors] = nil,
-            [itemKeys.startQuest] = nil,
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseItems.lua:2830]: These should also stay.

File: Database/Corrections/sodItemFixes.lua [hunk 7]
```diff
@@ -32,6 +32,12 @@ function SeasonOfDiscovery:LoadItems()
         [209846] = {
             [itemKeys.objectDrops] = {409692},
         },
+        [210187] = {
+            [itemKeys.objectDrops] = nil,
+            [itemKeys.itemDrops] = nil,
+            [itemKeys.vendors] = nil,
```
Comment (BreakBB) [inline Database/Corrections/sodItemFixes.lua:38]: And these can be removed (since we have them in the base file)

Comment (Sommos) [reply Database/Corrections/sodItemFixes.lua]: Fixed in: https://github.com/Questie/Questie/pull/5339/commits/b76ce8abcbab8297781523dc87d52c9a739b652f

File: Database/Corrections/Automatic/sodBaseItems.lua (hunk 6 above)
Comment (Sommos) [reply Database/Corrections/Automatic/sodBaseItems.lua]: Fixed in: https://github.com/Questie/Questie/pull/5339/commits/820f3e91d4908ff1dd233f342c8907524e7e1fd3

File: Database/Corrections/sodItemFixes.lua [hunk 8]
```diff
@@ -32,6 +32,9 @@ function SeasonOfDiscovery:LoadItems()
         [209846] = {
             [itemKeys.objectDrops] = {409692},
         },
+        [210187] = {
+            [itemKeys.startQuest] = {78270},
```
Comment (BreakBB) [inline Database/Corrections/sodItemFixes.lua:36]:
```suggestion
            [itemKeys.startQuest] = 78270,
```

Just noticed this needs to be a number, not a table.

You can verify that by using the "Recompile Database" function in the Advanced settings. That will scream at you when something is really broken.

File: Database/Corrections/SeasonOfDiscovery.lua [hunk 9]
```diff
@@ -175,7 +175,7 @@ local questsToBlacklistBySoDPhase = {
         [90078] = true, -- Hiding Warlock Demonic Grace Elwynn Forest for now as there are too many icons
         [90079] = true, -- Hiding Warlock Demonic Grace Durotar for now as there are too many icons
         [90080] = true, -- Hiding Warlock Demonic Grace Tirisfal Galdes for now as there are too many icons
-
+        [210187] = true, -- Hiding Rogue Deadly Brew Pre-req for now as there are too many icons
```
Comment (BreakBB) [inline Database/Corrections/SeasonOfDiscovery.lua:178]: Also this is the itemId, not the questId.
```suggestion
        [78270] = true, -- Hiding Rogue Deadly Brew Pre-req for now as there are too many icons
```

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 10]
```diff
@@ -399,6 +399,17 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+            [questKeys.name] = "Goblin Lockpicks",
+            [questKeys.startedBy] = {{3988, 4070, 3992, 3993}},
+            [questKeys.finishedBy] = {{4086}},
+            [questKeys.requiredLevel] = 1,
+            [questKeys.questLevel] = 23,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.ROGUE,
+            [questKeys.objectivesText] = {"Find The Horn of Xelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village."},
+            [questKeys.objectives] = nil,
+        },
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:412]:
```suggestion
        [78270] = {
            [questKeys.name] = "Goblin Lockpicks",
            [questKeys.startedBy] = nil,
            [questKeys.finishedBy] = {{4086,}},
            [questKeys.requiredLevel] = 1,
            [questKeys.questLevel] = 23,
            [questKeys.requiredRaces] = raceIDs.NONE,
            [questKeys.requiredClasses] = classIDs.ROGUE,
            [questKeys.objectivesText] = {"Find The Horn of Xelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village."},
            [questKeys.objectives] = {nil,nil,{{210187}}},
        },
```

Just replacing this with the result of the scraper.

File: Database/Corrections/sodQuestFixes.lua [hunk 11]
```diff
@@ -199,6 +199,9 @@ function SeasonOfDiscovery:LoadQuests()
         [78267] = {
             [questKeys.objectivesText] = {"Bring 16 Shredder Turbocharger to Grizzby."},
         },
+        [78270] = {
+            [questKeys.zoneOrSort] = sortKeys.ROGUE,
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:203]:
```suggestion
            [questKeys.startedBy] = {{4086}},
            [questKeys.zoneOrSort] = sortKeys.ROGUE,
```

File: Database/Corrections/sodItemFixes.lua [hunk 12]
```diff
@@ -32,6 +32,9 @@ function SeasonOfDiscovery:LoadItems()
         [209846] = {
             [itemKeys.objectDrops] = {409692},
         },
+        [210187] = {
+            [itemKeys.startQuest] = 78270,
+        },
```
Comment (BreakBB) [inline Database/Corrections/sodItemFixes.lua:37]:
```suggestion
```

**Review by BreakBB — COMMENTED** [review]
I just had another look at this quest, because it looked somewhat strange in the corrections.

So here is the things:

https://www.wowhead.com/classic/item=210187/venture-co-work-order do NOT start a quest. It is not an item you right click and get a quest. Instead you need this item for the "turn-in-only" quest https://www.wowhead.com/classic/quest=78270/goblin-lockpicks.

On top of that https://www.wowhead.com/classic/quest=78270/goblin-lockpicks is only available while the player currently have https://www.wowhead.com/classic/quest=78261/the-horn-of-xelthos in the quest log. Meaning 78270 is a `childQuest` of `78261`.

And here comes the issue: Since "Goblin Lockpicks" is a "turn-in-only" quest, it will never be in the quest log and therefore we can not show objectives for it.
Instead I suggest to change the `objectivesText` of that quest, to explain that you need to pickpocket the item from the Venture Co. mobs in the area.

Then we can also remove the blacklist again, because there are only two markers on the map.

**Comment by BreakBB** [comment]
Also this is the scraper result for the "Horn of Xelthos":

```lua
    [78261] = {
        [questKeys.name] = "The Horn of Xelthos",
        [questKeys.startedBy] = nil,
        [questKeys.finishedBy] = nil,
        [questKeys.requiredLevel] = 1,
        [questKeys.questLevel] = 23,
        [questKeys.requiredRaces] = raceIDs.NONE,
        [questKeys.requiredClasses] = classIDs.ROGUE,
        [questKeys.objectivesText] = {"Find The Horn of Xelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village. You must complete the job alone."},
        [questKeys.objectives] = {nil,nil,{{210183}}},
    },
```

**Comment by BreakBB** [comment]
Hey @Sommos 

here is what is left to do for this PR:

1. Add the quest listed in [this comment](https://github.com/Questie/Questie/pull/5339#issuecomment-1867360891) to the `sodBaseQuests` 
2. Add the `parentQuest` field to "Goblin Lockpicks", with the questId of "The Horn of Xelthos" (in `sodQuestFixes`)
3. Add the `childQuests` field to "The Horn of Xelthos", as table containing the questId of "Goblin Lockpicks" (in `sodQuestFixes`)
4. Change the objectiveText of "Goblin Lockpicks" to explain that you need to pickpocket the goblins in the area (in `sodQuestFixes`)
5. Add both quests to the `runeQuestsInSoD` table in `SeasonOfDiscovery`
6. Remove the questId of "Goblin Lockpicks" from the blacklist, since there won't be too many icons after the points above.

**Comment by Sommos** [comment]
Okay, all of those changes have now been pushed and added in to this PR. 

This has been a pain, sorry for any time wasted / issues caused!

File: Database/Corrections/SeasonOfDiscovery.lua [hunk 13]
```diff
@@ -66,6 +68,7 @@ local runeQuestsInSoD = {-- List quests here to have them flagged as Rune quests
     [79096] = true,
     [79097] = true,
 
+
```
Comment (BreakBB) [inline Database/Corrections/SeasonOfDiscovery.lua:71]:
```suggestion
```

**Review by BreakBB — COMMENTED** [review]
Good job on your last fixes! I only moved some minor things around. Feel free to merge the suggestions or keep asking questions.

Please don't worry about the time this PR used. You picked a hard one and we are not in a hurry 😁

**Comment by Sommos** [comment]
Everything should now be working as intended, and is ready to merge when you're happy!

Just a case of a bad one to pick up for my 5th/6th issue to resolve. 😁

**Review by BreakBB — APPROVED** [review]
Thanks a lot @Sommos for keeping this up and continue working on it. You did a hell of a job on this 💪🏻
