### PR TITLE
[locale] Update UI translations to use "Party" instead of "Group" for the Announcement options

### LINKED ISSUE #4083: Announcements are Broken in Latest Build
image

I have announcements turned on but they are not announcing that I picked up the item.

### PR DESCRIPTION
**Pull request by BreakBB**
## Issue references

Fixes #4083

## Proposed changes

- "Group" setting is renamed to "Party"

### CODE REVIEW

File: Localization/Translations/Generics.lua [hunk 1]
```diff
@@ -386,6 +386,18 @@ local genericsLocales = {
...
+    ["Party"] = {
+        ["ptBR"] = nil,
+        ["ruRU"] = nil,
+        ["deDE"] = nil,
+        ["koKR"] = nil,
+        ["esMX"] = nil,
+        ["enUS"] = true,
+        ["zhCN"] = nil,
+        ["zhTW"] = nil,
+        ["esES"] = nil,
```
Comment (BreakBB) [inline Localization/Translations/Generics.lua:398]:
```suggestion
        ["esES"] = "Grupo",
```

File: Localization/Translations/Generics.lua [hunk 2]
```diff
@@ -386,6 +386,18 @@ local genericsLocales = {
         ["esES"] = "Grupo",
         ["frFR"] = "Groupe",
     },
+    ["Party"] = {
+        ["ptBR"] = nil,
+        ["ruRU"] = nil,
+        ["deDE"] = nil,
+        ["koKR"] = nil,
+        ["esMX"] = nil,
```
Comment (BreakBB) [inline Localization/Translations/Generics.lua:394]:
```suggestion
        ["esMX"] = "Grupo",
```

File: Localization/Translations/Generics.lua [hunk 3]
```diff
@@ -386,6 +386,18 @@ local genericsLocales = {
         ["esES"] = "Grupo",
         ["frFR"] = "Groupe",
     },
+    ["Party"] = {
+        ["ptBR"] = nil,
+        ["ruRU"] = nil,
```
Comment (BreakBB) [inline Localization/Translations/Generics.lua:391]:
```suggestion
        ["ruRU"] = "Группа",
```

File: Localization/Translations/Options/Social.lua [hunk 4]
```diff
@@ -38,17 +38,17 @@ local socialOptionsLocales = {
         ["esES"] = "Anuncio de misión",
         ["esMX"] = "Anuncio de misión",
     },
-    ["Announce quest updates to other players in your group or raid"] = {
+    ["Announce quest updates to other players in your group"] = {
         ["ptBR"] = nil,
-        ["ruRU"] = "Включает оповещения об обновлениях заданий в чатах группы и/или рейда",
-        ["frFR"] = "Annoncer les mises à jour des quêtes aux autres joueurs du groupe ou du raid",
+        ["ruRU"] = nil,
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:43]:
```suggestion
        ["ruRU"] = "Включает оповещения об обновлениях заданий в чате группы",
```

File: Localization/Translations/Generics.lua [hunk 5]
```diff
@@ -386,6 +386,18 @@ local genericsLocales = {
...
+        ["ptBR"] = nil,
+        ["ruRU"] = "Группа",
+        ["deDE"] = nil,
+        ["koKR"] = nil,
+        ["esMX"] = "Grupo",
+        ["enUS"] = true,
+        ["zhCN"] = nil,
+        ["zhTW"] = nil,
+        ["esES"] = "Grupo",
+        ["frFR"] = nil,
```
Comment (BreakBB) [inline Localization/Translations/Generics.lua:399]:
```suggestion
        ["frFR"] = "Groupe",
```

File: Localization/Translations/Options/Social.lua [hunk 6]
```diff
@@ -38,17 +38,17 @@ local socialOptionsLocales = {
         ["esES"] = "Anuncio de misión",
         ["esMX"] = "Anuncio de misión",
     },
-    ["Announce quest updates to other players in your group or raid"] = {
+    ["Announce quest updates to other players in your group"] = {
         ["ptBR"] = nil,
-        ["ruRU"] = "Включает оповещения об обновлениях заданий в чатах группы и/или рейда",
-        ["frFR"] = "Annoncer les mises à jour des quêtes aux autres joueurs du groupe ou du raid",
+        ["ruRU"] = "Включает оповещения об обновлениях заданий в чате группы",
+        ["frFR"] = "Annoncer les mises à jour des quêtes aux autres joueurs du groupe",
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:44]:
```suggestion
        ["frFR"] = "Annoncer l'avancée des quêtes aux autres membres de votre groupe.",
```
