### PR TITLE
[quest] Fix 'Tool Bucket' Spawn Locations

### LINKED ISSUE #6130: Quest Marker Incorrectly Placed - Nugget Slugs
## Bug description

The item markers are incorrect for the item Nugget Slugs. This is a list of the new spawn location co-ords:

40.75, 33.22
40.74, 33.38
40.65, 33.46
40.44, 32.85
41.00, 32.98
41.49, 32.08
41.90, 32.09
42.07, 32.31
42.14, 31.90
42.48, 31.92
42.72, 31.82
42.98, 32.12
42.69, 32.68
42.19, 32.65
43.12, 31.49
43.04, 30.90

## Screenshots

image

## Questie & WoW version

Cata Classic
Questie Version 10.3.3

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #6130

## Proposed changes

- Add a fix to spawn locations for Tool Bucket as part of the Nugget Slugs quest.

### CODE REVIEW

**Comment by BreakBB** [comment]
In Cataclysm the zone ID for "Nothern Barrens", is the same as for "The Barrens" before Cataclysm. So your initial ID was correct.

File: Database/Corrections/cataObjectFixes.lua [hunk 1]
```diff
@@ -23,9 +23,12 @@ function CataObjectFixes.Load()
         [144052] = { -- Sandsorrow Watch Water Hole
             [objectKeys.name] = "Sandsorrow Watch Water Hole",
         },
-        [154357] = {
+        [154357] = { -- Glinting Mud
             [objectKeys.spawns] = {[zoneIDs.REDRIDGE_MOUNTAINS]={{25.88,47.15},{23.94,49.78},{34.8,49.43},{32.07,51.94},{19.77,47.27},{27.09,50.94},{35.73,49.6},{35.71,49.6},{21.92,48.48}}},
         },
+        [161752] = { -- Tool Bucket
+            [objectKeys.spawns] = {[zoneIDs.NORTHERN_BARRENS]={{40.75,33.22},{40.74,33.38},{40.65,33.46},{40.44,32.85},{41.00,32.98},{41.49,32.08},{41.90,32.09},{42.07,32.31},{42.14,31.90},{42.48,31.92},{42.72,31.82},{42.98,32.12},{42.69,32.68},{42.19,32.65},{43.12,31.49},{43.04,30.90}}},
```
Comment (BreakBB) [inline Database/Corrections/cataObjectFixes.lua:30]:
```suggestion
            [objectKeys.spawns] = {[zoneIDs.THE_BARRENS]={{40.75,33.22},{40.74,33.38},{40.65,33.46},{40.44,32.85},{41.00,32.98},{41.49,32.08},{41.90,32.09},{42.07,32.31},{42.14,31.90},{42.48,31.92},{42.72,31.82},{42.98,32.12},{42.69,32.68},{42.19,32.65},{43.12,31.49},{43.04,30.90}}},
```
