### PR TITLE
[quest] Fix 'Stolen Silver' Spawn Locations

### LINKED ISSUE #6128: Quest Marker Incorrectly Placed - The Stolen Silver
## Bug description

The map marker for Stolen Silver is in the wrong place. 
Current (incorrect) co-ords: 57.99, 54.14
Correct co-ords: 63.72, 58.80

## Screenshots

image

## Questie & WoW version

Cata Classic
Questie Version 10.3.3

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #6128

## Proposed changes

- Add a fix to spawn locations for Stolen Silver as part of the The Stolen Silver quest.

### CODE REVIEW

File: Database/Corrections/cataObjectFixes.lua [hunk 1]
```diff
@@ -23,6 +23,9 @@ function CataObjectFixes.Load()
         [144052] = { -- Sandsorrow Watch Water Hole
             [objectKeys.name] = "Sandsorrow Watch Water Hole",
         },
+        [147557] = { -- Stolen Silver
+            [objectKeys.spawns] = {[zoneIDs.NORTHERN_BARRENS]={{63.72,58.80}}},
```
Comment (BreakBB) [inline Database/Corrections/cataObjectFixes.lua:27]:
```suggestion
            [objectKeys.spawns] = {[zoneIDs.THE_BARRENS]={{63.72,58.80}}},
```
