### PR TITLE
[quest] Southern Barrens quest fixes (Cata)

### LINKED ISSUE #6381: Quest Issue - A Family Divided (Cata - Southern Barrens)
## Description

Questie shows as available before prequest completed

According to Wowhead prequest is From Bad to Worse but will check in game
## Wowhead link

https://www.wowhead.com/cata/quest=24543/a-family-divided

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6382: Quest Issue - Winnoa Pineforest (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=24807/winnoa-pineforest

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6383: Quest Issue - Sowing a Solution (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed
No quest objective markers

## Wowhead link

https://www.wowhead.com/cata/quest=24566/sowing-a-solution

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6384: Quest Issue - Siegebreaker (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=24569/siegebreaker

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6385: Quest Issue - A Line in the Dirt (Cata - Southern Barrens) #6382
## Description

Quest is available but not appearing in Questie
No objectives shown

## Wowhead link

https://www.wowhead.com/cata/quest=24546/a-line-in-the-dirt
## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6386: Quest Issue - Claim The Battle Scar (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=24618/claim-the-battle-scar

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6387: Quest Issue - Intelligence Warfare (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=24634/intelligence-warfare

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6388: Quest Issue - Mahka's Plea (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=24633/mahkas-plea
## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6389: Quest Issue - Next of Kin (Cata - Southern Barrens)
## Description

Questie showing as available before prequest completed

## Wowhead link

https://www.wowhead.com/cata/quest=25292/next-of-kin

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6390: Quest Issue - A Weezil in the Henhouse (Cata - Southern Barrens)
## Description

Available in game but not shown by Questie

## Wowhead link

https://www.wowhead.com/cata/quest=24684/a-weezil-in-the-henhouse

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6391: Quest Issue - Warriors' Redemption (Cata - Southern Barrens)
## Description

No objective markers shown on map

## Wowhead link

https://www.wowhead.com/cata/quest=24512/warriors-redemption

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6392: Quest Issue - The Low Road (Cata - Southern Barrens)
## Description

Start (item drop) not marked on map

## Wowhead link

https://www.wowhead.com/cata/quest=24518/the-low-road

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6393: Quest Issue - Stalling the Survey (Cata - Southern Barrens)
## Description

Patrol path for quest npc missing

{42.57,22.30},{41.87,22.25},{41.64,21.56},{41.59,21.28},{41.41,20.36},{41.33,19.33},{40.63,18.26},{40.52,17.90},{40.43,17.31},{40.58,16.28},{40.62,15.49},{40.67,15.07},

## Wowhead link

https://www.wowhead.com/cata/quest=24519/stalling-the-survey

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6394: Quest Issue - Adder Subtraction (Cata - Southern Barrens)
## Description

Missing objectives

## Wowhead link

https://www.wowhead.com/cata/quest=24570/adder-subtraction

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6396: Quest Issue - Desolation Hold Inspection (Cata - Southern Barrens)
## Description

No objectives

## Wowhead link

https://www.wowhead.com/cata/quest=24577/desolation-hold-inspection

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6397: Quest Issue - The Butcher of Taurajo (Cata - Southern Barrens)
## Description

Add extra objective talk to Karthog (48.15,58.20) to trigger event

## Wowhead link

https://www.wowhead.com/cata/quest=24637/the-butcher-of-taurajo

## Questie & WoW version

Cata
Questie 10.3.12

### LINKED ISSUE #6398: Quest Issue - Tauren Vengeance (Cata - Southern Barrens)
## Description

https://www.wowhead.com/cata/npc=3341/gann-stonespire is shown in both Barrens and Southern Barrens, but actually only in Southern Barrens (due to Cata zone split)
## Wowhead link

https://www.wowhead.com/cata/quest=24632/tauren-vengeance

## Questie & WoW version

Cata
Questie 10.3.12

### PR DESCRIPTION
**Pull request by coldpasta123**
## Issue references

Fixes #6381 
Fixes #6382 
Fixes #6386 
Fixes #6387 
Fixes #6388 
Fixes #6389 
Fixes #6390 
Fixes #6392 
Fixes #6393 
Fixes #6398
Fixes #6396 
Fixes #6394 
Fixes #6383
Fixes #6385 
Fixes #6397 
Fixes #6384 
Fixes #6391 

## Proposed changes

- Add prequest for A Family Divided
- Add prequest for Claim the Battle Scar
- Add prequest for Winnoa Pineforest
- Add prequest for Intelligence Warfare
- Add prequest for Mahka's Plea
- Add prequest for Next of Kin
- Remove non-mandatory prequest for A Weezil in the Henhouse 
- Fix quest start for The Low Road 
- Add patrol path for Henry Zykes
- Fix location for Gann Stonespire
- Add objective for Desolation Hold Inspection
- Add drop location for Adder Subtraction
- Add prequests for Sowing a Solution
- Remove non-mandatory prequest for A Line in the Dirt
- Add objectives for A Line in the Dirt
- Add event trigger marker for The Butcher of Taurajo
- Add prequests for Siegebreaker
- Add objectives for Warriors' Redemption

### CODE REVIEW

**Comment by coldpasta123** [comment]
@Sommos lots of fixes here - we should avoid duplicating...

File: Localization/Translations/ExtraObjectives/CataObjectives.lua [hunk 1]
```diff
@@ -2666,6 +2666,18 @@ local cataObjectiveLocales = {
...
+        ["ruRU"] = false,
+        ["deDE"] = false,
+        ["koKR"] = false,
+        ["esMX"] = false,
+        ["enUS"] = true,
+        ["frFR"] = false,
+        ["esES"] = false,
+        ["zhTW"] = false,
+        ["zhCN"] = false,
+    },
```
Comment (BreakBB) [inline Localization/Translations/ExtraObjectives/CataObjectives.lua:2680]:
```suggestion
    ["Acquire crates of Confiscated Arms"] = {
        ["ptBR"] = false,
        ["ruRU"] = false,
        ["deDE"] = false,
        ["koKR"] = false,
        ["esMX"] = false,
        ["enUS"] = true,
        ["frFR"] = false,
        ["esES"] = false,
        ["zhTW"] = false,
        ["zhCN"] = false,
    },
    ["Speak with Karthog to lure out General Hawthorne"] = {
        ["ptBR"] = false,
        ["ruRU"] = false,
        ["deDE"] = false,
        ["koKR"] = false,
        ["esMX"] = false,
        ["enUS"] = true,
        ["frFR"] = false,
        ["esES"] = false,
        ["zhTW"] = false,
        ["zhCN"] = false,
    },
```
