### PR TITLE
[quest] Stonetalon quest fixes (Cata)

### LINKED ISSUE #5955: Missing objective data for quest 25891: Last Ditch Effort (Cataclysm Classic/Stonetalon Mountains)
## Bug description

Hey folks! I'm running through Stonetalon Mountains now in Cataclysm Classic and got the following error:

Questie: [ERROR] Missing objective data for quest 25891 Last Ditch Effort Made

## Screenshots

Error message:
image

Quest Description:

image

## Questie & WoW version

Questie 10.0.7
WoW 4.4.0 (Cataclysm Classic)

### LINKED ISSUE #6349: Quest Issue - We're Here to Do One Thing, Maybe Two... (Cata - Stonetalon)
## Description

We're Here to Do One Thing, Maybe Two...

- Quest is available but not showing as available in Questie
- Questie not recognising objective as complete when ready to turn in

## Wowhead link

https://www.wowhead.com/cata/quest=25945/were-here-to-do-one-thing-maybe-two

## Screenshots

image

## Questie & WoW version

Cata
Questie 10.3.10

### LINKED ISSUE #6350: Quest Issue - Barrier to Entry (Cata - Stonetalon)
## Description

Quest objective marker incorrectly placed. There are interactable 'objects' - Krom'gar Elf Killer north of the camp, but not in DB as objects

## Wowhead link

https://www.wowhead.com/cata/quest=25999/barrier-to-entry
## Screenshots

image

### LINKED ISSUE #6351: Quest Issue - Lessons from the Lost Isles (Cata - Stonetalon)
## Description

Lessons from the Lost Isles missing prequest - requires Barrier to Entry

## Wowhead link

https://www.wowhead.com/cata/quest=26003/lessons-from-the-lost-isles
https://www.wowhead.com/cata/quest=25999/barrier-to-entry

### LINKED ISSUE #6352: Quest Issues - Krom'gar Fortress Prequests (Cata - Stonetalon)
## Description

Not available - prequest TBC when I get there :)

## Wowhead link

https://www.wowhead.com/cata/quest=26011/enemy-of-the-horde-marshal-paltrow
https://www.wowhead.com/cata/quest=26026/dream-of-a-better-tomorrow
https://www.wowhead.com/cata/quest=28084/might-of-the-kromgar
https://www.wowhead.com/cata/quest=26009/seek-and-destroy
https://www.wowhead.com/cata/quest=26010/ashes-to-ashes
https://www.wowhead.com/cata/quest=26047/and-thats-why-they-call-them-peons
https://www.wowhead.com/cata/quest=26048/spare-parts-up-in-here
https://www.wowhead.com/cata/quest=26046/between-a-rock-and-a-hard-place 

## Questie & WoW version

Cata
Questie 10.3.10

### LINKED ISSUE #6353: Quest Issues - Cliffwalker Post Prequests (Cata - Stonetalon)
## Description

Requires prequests - TBC

## Wowhead link

https://www.wowhead.com/cata/quest=26134/nothing-left-for-you-here
https://www.wowhead.com/cata/quest=26097/proof-of-lies
https://www.wowhead.com/cata/quest=26099/is-this-justice

## Questie & WoW version

Cata
Questie 10.3.10

### LINKED ISSUE #6354: Quest Issues - Malaka'Jin Prequests (Cata - Stonetalon)
## Description

Requires prequests - TBC

## Wowhead link

https://www.wowhead.com/cata/quest=26061/da-voodoo-ram-horns
https://www.wowhead.com/cata/quest=26062/da-voodoo-resonite-crystal
https://www.wowhead.com/cata/quest=26060/da-voodoo-stormer-heart
https://www.wowhead.com/cata/quest=26073/alls-quiet-on-the-southern-front
https://www.wowhead.com/cata/quest=26066/reinforcements
https://www.wowhead.com/cata/quest=26064/fight-on-their-stomachs

## Questie & WoW version

Cata
Questie 10.3.10

### LINKED ISSUE #6375: Quest Issue - Reinforcements (Cata - Stonetalon)
## Description

No objectives 

## Wowhead link

https://www.wowhead.com/cata/quest=26066/reinforcements

### LINKED ISSUE #6376: Quest Issue - Seek and Destroy (Cata - Stonetalon)
## Description

Wowhead comments suggest quest only available before revered Org rep. Definitely not available on char at max rep. Need to validate in game.

## Wowhead link

https://www.wowhead.com/cata/quest=26009/seek-and-destroy

### LINKED ISSUE #6378: Quest Issue - Final Delivery (Cata - Stonetalon)
## Description

No quest objectives

Use https://www.wowhead.com/cata/npc=41418/kromgar-hot-air-balloon at 51.17, 45.50

## Wowhead link

https://www.wowhead.com/cata/quest=26077/final-delivery

## Questie & WoW version

Cata
Questie 10.3.12

### PR DESCRIPTION
**Pull request by coldpasta123**
## Issue references

Fixes #6352
Fixes #6351 
Fixes #6354 
Fixes #6353 
Fixes #6350 
Fixes #6349 
Fixes #5955 
Fixes #6375 
Fixes #6376 
Fixes #6378 

## Proposed changes

- Added prequest requirements for several Krom'gar Fortress quests
- Added prequest for Lessons from the Lost Isles
- Added prequests for several Malaka'Jin quests
- Added prequests for several Cliftwalker Post quests
- Added objectives for Barrier to Entry
- Fix prequests for We're Here to Do One Thing, Maybe Two...
- Added objectives for Last Ditch Effort 
- Added objectives for Reinforcements...
- Added max rep requirement for Seek and Destroy
- Added objectives for Final Delivery

### CODE REVIEW

File: Database/Corrections/cataQuestFixes.lua [hunk 1]
```diff
@@ -7273,7 +7338,8 @@ function CataQuestFixes.Load()
         },
         [28532] = { -- Warchief's Command: Stonetalon Mountains!
             [questKeys.requiredMaxLevel] = 28,
-        },
+            [questKeys.exclusiveTo] = {25945},
+          },
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:7342]:
```suggestion
        },
```

**Review by BreakBB — APPROVED** [review]
