### PR TITLE
[fix] Handle quests with many starters

### LINKED ISSUE #2564: Missing quest drop item - The Powers Below
[The Powers Below](https://classic.wowhead.com/quest=968/the-powers-below)
Starts from a book
[The Powers Below](https://classic.wowhead.com/item=5352/book-the-powers-below)
Dropped by
[Twilight Disciple](https://classic.wowhead.com/npc=2338/twilight-disciple)
and
[Twilight Thug](https://classic.wowhead.com/npc=2339/twilight-thug)
both Darkshore - Wowhead map coordinated are fine
Turn in
[Gerrig Bonegrip](https://classic.wowhead.com/npc=2786/gerrig-bonegrip)

Hope this helps

### LINKED ISSUE #2975: The Powers Below (968)
Version 6.3.16

This quest is started from an item (Book: The Powers Below (5352)) dropped by mobs in the Master's Glaive and probably in the base of the Cave Mushrooms cave.

Twilight Disciples (2338) and Twilight Thugs (2339) - Wowhead has some coordinates.

As far as I can see, there are no coordinates/clue as to the item's occurrence in your database.

### LINKED ISSUE #2976: The Powers Below (968) - further thoughts
Surely you do not need an icon for each NOC's occurrence, just representative ones in each location? Wholly/Grail use one icon at each corner of the Master's Grave and one in the cave in the north. At least the NPCs should be mentioned in the text description on the search parts.

_Originally posted by @Nerillida in https://github.com/Questie/Questie/issues/2975#issuecomment-869008586_

### LINKED ISSUE #5443: SoD runes
## Description

# Druid

- Living Seed ✅ 
- Wild Strikes ⏳ (needs #5362)
- Fury of Stormrage ✅ 
- Survival of the Fittest ✅ 
- Starsurge ✅ 
- Lifebloom ✅ 
- Skull Bash ✅ 
- Savage Roar ✅ 
  -  Westfall location ⌛ (needs #5362)
- Sunfire ✅ 
- Lacerate ✅ 
  - Darkshore location ⌛ (needs #5362)
- Wild Growth ✅ 
- Mangle ✅ 
  - Mulgore location ⌛ (needs #5362)

# Hunter

- Heart of the Lion ✅ 
- Master Marksman ✅ 
- Lone Wolf ✅ 
- Cobra Strikes ✅ 
- Kill Command ✅ 
- Sniper Training ✅ 
- Serpent Spread ✅ 
- Flanking Strikes ✅ 
- Beast Mastery ✅ 
  - Silverpine Forest location ⌛ (needs #5362)
- Chimera Shot ✅ 
- Explosive Shot ✅ 
- Carve ⌛ (needs #5362)

# Mage

- Burnout ✅ 
- Fingers of Frost ✅ 
- Regeneration ✅ 
- Enlightment ⌛ (needs #5362)
- Icy Veins ✅ 
- Arcane Surge ✅ 
- Mass Regeneration ✅ 
- Living Flame ⌛ (needs #5362)
- Rewind Time ✅ 
- Living Bomb ⌛ (needs #5362)
- Arcane Blast ✅ 
- Ice Lance  ✅ 

# Paladin

- Seal of Martyrdom ✅ 
- Divine Storm ✅ 
- Horn of Lordaeron ✅ 
- Aegis ✅ 
- Divine Sacrifice ✅ 
- Inspiration Exemplar ✅ 
- Avenger's Shield ✅ 
- Exorcist ⌛ (needs #5362)
- Rebuke ✅ 
- Beacon of Light ✅ 
- Crusader Strike ✅ 
- Hand of Reckoning ✅ 
  - Westfall location ⌛ (needs #5362)

# Priest

- Void Plague ✅
  - Dun Morogh, Durotar and Teldrassil location ⌛ (needs #5362)
- Serendipity ✅ 
- Strength of Soul ✅ 
- Twisted Faith ✅ 
  - The Barrens location ⌛ (needs #5362)
- Power Word: Barrier ⌛ (needs #5362)
- Shared Pain ✅ 
  - Elwynn Forest location ⌛ (needs #5362)
  - Tirisfal Glades location ⌛ (needs #5362)
- Homunculi ✅ 
  - Dun Morogh location ⌛ (needs #5362)
  - Elwynn Forest location ⌛ (needs #5362)
  - Teldrassil location ⌛ (needs #5362)
  - Durotar location ⌛ (needs #5362)
  - Tirisfal Glades location ⌛ (needs #5362)
- Prayer of Mending ✅ 
- Penance ✅ 
- Mind Sear ✅ 
- Circle of Healing ⌛ (needs #5362)
- Shadow Word: Death ✅ 

# Rogue

- Deadly Brew ✅ 
- Just a Flesh Wound ✅ 
- Quick Draw ✅ 
- Slaughter from the Shadows ✅ 
- Between the Eyes ✅ 
- Blade Dance ✅ 
  - Loch Modan location ⌛ (needs #5362)
- Envenom ⌛ (needs #5362)
- Mutilate ✅ 
  - Teldrassil location ⌛ (needs #5362)
  - Dun Morogh location ⌛ (needs #5362)
- Shadowstrike ✅ 
- Saber Slash ✅ 
- Shiv ⌛ (needs #5362)
- Main Gauche ✅ 

# Shaman

- Dual Wield Specialization ✅ 
- Shield Mastery ✅ 
- Overload ✅ 
- Healing Rain ✅ 
- Ancestral Guidance ✅ 
- Earth Shield ✅ 
- Way of Earth ⌛ (needs #5362)
- Shamanistic Rage ✅ 
- Water Shield ✅ 
- Lava Burst ⌛ (needs #5362)
- Lava Lash ✅ 
- Molten Blast ✅ 

# Warlock

- Lake of Fire ✅ 
- Master Channeler ✅ 
  - Westfall location ⌛ (needs #5362)
- Soul Siphon ✅ 
- Demonic Tactics ✅ 
- Everlasting Affliction ✅ 
- Incinerate ✅ 
- Demonic Grace ✅ 
- Demonic Pact ✅ 
- Metamorphosis ✅ 
- Shadow Bolt Volley ✅ 
- Chaos Bolt ✅ 
- Haunt ✅ 

# Warrior

- Flagellation ✅ 
- Blood Frenzy ✅ 
- Raging Blow ✅ 
- Warbringer ✅ 
- Furious Thunder ✅ 
- Consumed by Rage ✅ 
- Frenzied Assault ✅ 
- Victory Rush ✅ 
- Endless Rage ✅ 
- Devastate ✅ 
- Single-Minded Fury ✅ 
- Quick Strike ✅ 
  - Loch Modan and Westfall ⌛ (needs #5362)

### PR DESCRIPTION
**Pull request by BreakBB**
## Issue references

Related to #317

Fixes #2564
Fixes #2975
Fixes #2976
Fixes #5443

## TODOs
- [x] Improve the initial logic below, to remove the fake NPCs again (this is too tedious)
  - Maybe a good first step is to just take the first spawn for each zone for each NPC?
  - If a starter for a quest has multiple spawns (more than 3 maybe?), then mark it as "quest with many starters"
- [x] Do we need a way to hide spawns for specific mobs/quests?
  - For runes like #5510 you need to kill _any_ bird in the zone for meat and then use the meat. Do we really want to show the birds on the map or just the tooltips on these mobs?

## Proposed changes

- The first spawns of each starter NPC is always added
- Each following spawn is only added if the distance to all previously added spawns of that NPC is far enough

## Screenshots

Before:
grafik

After:
grafik

### CODE REVIEW

File: Database/QuestieDB.lua [hunk 1]
```diff
@@ -1447,3 +1447,39 @@ QuestieDB.waypointPresets = {
...
 }
+
+
+local questsWithTooManyStarters = {
```
Comment (BreakBB) [inline Database/QuestieDB.lua:1452]: Remove this.
