### PR TITLE
[quest] ADDED: 'The Horn of Xelthos' Now Has ZoneID Link

### LINKED ISSUE #5420: [quest] 'The Horn of Xelthos' Missing Correct Zone Name
## Description

The SoD quest 'The Horn of Xelthos' is currently showing 'Unknown Zone' in the place of 'Shadowfang Keep' in the tracker.

## Wowhead link

https://www.wowhead.com/classic/quest=78261/the-horn-of-xelthos

### Discord Bug Report

Quest ID: 78261
Quest Name: The Horn of Xelthos
Quest Text: "Find The Horn of Zelthos inside of Shadowfang Keep. Then, return it to C's dead drop near Pyrewood Village. You must complete the job alone."
Objective Text: "Horn of Xelthos 0/1"
Character: Lvl 25 HUMAN ROGUE
Client: 1.15.0 SoD
Questie: v9.2.13
Locale: enUS

## Screenshots

image

## Questie & WoW version

v9.2.13
WoW Classic SoD - v1.15.052409

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #5420

## Proposed changes

- ADDED: 'The Horn of Xelthos' now has a zoneID so the subtitle should now show `Shadowfang Keep` instead of `Unknown Zone` in the tracker.

### CODE REVIEW

File: Database/Corrections/sodQuestFixes.lua [hunk 1]
```diff
@@ -344,6 +344,7 @@ function SeasonOfDiscovery:LoadQuests()
             [questKeys.objectivesText] = {"Bring symbols of the three owls to Loganaar in Moonglade. NOTE: To accept this quest, you need to bring at least one symbol, but you can also bring all three at once."},
         },
         [78261] = {
+            [questKeys.zoneOrSort] = zoneIDs.SHADOWFANG_KEEP,
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:347]: In the quest log, this quest is in the "Rogue" category. So we want to also show it as such.

```suggestion
            [questKeys.zoneOrSort] = sortKeys.ROGUE,
```

Comment (BreakBB) [reply Database/Corrections/sodQuestFixes.lua]: It has to be `sortKeys`, not `zoneIDs`.

Comment (Sommos) [reply Database/Corrections/sodQuestFixes.lua]: Fixed in: https://github.com/Questie/Questie/pull/5430/commits/d1feee465f4669af7fb9cf052e43c65ae7369974

That was an oversight. Sorry about that! Should be good now.
