### PR TITLE
[fix] Fix lagging when leaving combat while on a timed quest

### LINKED ISSUE #2592: Microstutter when doing the quest "Need for a Cure"
## Bug description

This was reported on Discord lately. When doing the quest [https://classic.wowhead.com/quest=812/need-for-a-cure](Need for a a Cure) microstutters were reported. This is most likely linked to the timer since the quest has a time limit.

## Questie version

v6.2.5

### PR DESCRIPTION
**Pull request by BreakBB**
Fixes #2592

This also fixed that the Tracker does not show objectives on times quest.

### CODE REVIEW

File: Modules/Tracker/QuestieQuestTimers.lua [hunk 1]
```diff
@@ -20,14 +15,14 @@ function QuestieQuestTimers:Initialize()
...
+            hooksecurefunc("QuestTimerFrame_Update", _QuestieQuestTimers.UpdateTimerFrame)
         end)
     else
-        hooksecurefunc("QuestTimerFrame_Update", _UpdateTimerFrame)
+        hooksecurefunc("QuestTimerFrame_Update", _QuestieQuestTimers.UpdateTimerFrame)
     end
 
     QuestTimerFrame:HookScript("OnShow", function()
-        QuestieQuestTimers.defaultBlizzPoint = {QuestTimerFrame:GetPoint()}
+        blizzardTimerLocation = { QuestTimerFrame:GetPoint()}
```
Comment (BreakBB) [inline Modules/Tracker/QuestieQuestTimers.lua:25]:
```suggestion
        blizzardTimerLocation = {QuestTimerFrame:GetPoint()}
```
