### PR TITLE
[db] Captured Tuskarr Prisoner - fix location

### LINKED ISSUE #6634: NPC 25636 "Captured Tuskarr Prisoner" wrong location
### Description

https://www.wowhead.com/cata/npc=25636/captured-tuskarr-prisoner

XXX

### Questie version

v10.6.4

### Game flavor

Cata

### PR DESCRIPTION
**Pull request by TorpedoCXC**
Also improve formatting

## Issue references

Fixes #6634

### CODE REVIEW

File: Database/Corrections/cataNPCFixes.lua [hunk 1]
```diff
@@ -848,16 +848,19 @@ function CataNpcFixes.Load()
...
             [npcKeys.spawns] = {
-                [zoneIDs.ASHENVALE]={
+                [zoneIDs.ASHENVALE] = {
                     {15.5,19.0,phases.EARTHEN_GUIDE_BFD},
                     {9.36,12.99,phases.EARTHEN_GUIDE_SHORE},
                 },
             },
         },
+        [25636] = { -- Captured Tuskarr Prisoner
+            [npcKeys.spawns] = {[zoneIDs.BOREAN_TUNDRA] = {{44,77.8}}},
```
Comment (BreakBB) [inline Database/Corrections/cataNPCFixes.lua:862]:
```suggestion
            [npcKeys.spawns] = {[zoneIDs.BOREAN_TUNDRA] = {{44.10,77.90}}},
```
