### PR TITLE
Bundle of wotlk quest fixes 9/28

### LINKED ISSUE #3740: Missing objective data for "Emergency Supplies"
## Wowhead link

https://www.wowhead.com/wotlk/quest=11887/emergency-supplies

### LINKED ISSUE #4220: Questie: [ERROR] Missing objective data for quest 11887 and objective Gnomish Emergency Toolkit

### LINKED ISSUE #4224: [ERROR] [QuestieQuest]: [Tooltips] There was an error populating objectives for Restless Soul Freed 13110 0 No error
## Bug description

Everytime I come out of loadingscreen or load in to my char this error appears in chat, questie seems to be working fine except this spamming my chat. 

## Screenshots

image

## Questie & WoW version

Using Latest questie 7.2.3 on WotLK Classic

### LINKED ISSUE #4232: WOTHK - Mob ID's are swapped for "An Issue of Trust"
## Bug description
The mob ID's are swapped so killing Bonesythe Ravager's counts towards the Blighted Corpse count and vise versa on your tooltips / map icons.

## Screenshots
image
image

## Questie & WoW version
Questie: v7.2.3
WoW: WOTLK

### LINKED ISSUE #4236: [[71] Mimicking Nature's Call (11281)] - objective in the wrong place
image

The spot on the bridge is wrong.

Should only have one spot for this quest.

### PR DESCRIPTION
**Pull request by Yttrium-tYcLief**
Fixes quests:
11281
11310
11671
11865
11881
11887
12561

Fix #4232 
Fix #4224
Fix #4220
Fix #3740
Fix #4236

### CODE REVIEW

**Comment by Yttrium-tYcLief** [comment]
Of note, with this PR, Howling Fjord horde-side should be 100% fixed. Working on Borean Tundra now, which is in way better shape but still has some outliers.

File: Database/Corrections/Wotlk/wotlkQuestFixes.lua [hunk 1]
```diff
@@ -257,6 +267,12 @@ function QuestieWotlkQuestFixes:Load()
         [11670] = {
             [questKeys.objectives] = {{{25430,"Warsong Banner Planted in Magmothregar"},},nil,{{34870,nil},},nil,},
         },
+        [11671] = {
+            [questKeys.extraObjectives] = {
+				{nil, ICON_TYPE_SLAY, l10n("Kill Inquisitor Salrand"), 0, {{"monster", 25584}}},
+                {{[zoneIDs.BOREAN_TUNDRA]={{41.8,39.1}}}, ICON_TYPE_EVENT, l10n("Use Beryl Shield Detonator"),},
+            },
```
Comment (BreakBB) [inline Database/Corrections/Wotlk/wotlkQuestFixes.lua:274]:
```suggestion
            [questKeys.extraObjectives] = {
                {nil, ICON_TYPE_SLAY, l10n("Kill Inquisitor Salrand"), 0, {{"monster", 25584}}},
                {{[zoneIDs.BOREAN_TUNDRA]={{41.8,39.1}}}, ICON_TYPE_EVENT, l10n("Use Beryl Shield Detonator"),},
            },
```

**Review by BreakBB — APPROVED** [review]
