### PR TITLE
[fix] fixed missing default and conditional check on Objectives announcement

### LINKED ISSUE #3492: Quest Announce is Broken
I suspect you guys are doing this on purpose, but in the even that you just didn't test any of this before releasing it... quest announce is off by default for new installs of Questie.

Also, when you select "announce on quest completed" it also announce on quest turn in. The double announce is just annoying, was never the original intent of the Quest Announce feature.

### PR DESCRIPTION
**Pull request by lbuchholz79**
## Issue references

partially fixes #3492 by restoring default to objective progress announce and have it depend on the ui toogle

## Proposed changes

- added `Questie.db.char.questAnnounceObjectives` in migration step based on old value of `Questie.db.char.questAnnounce`
- added new migration step to default `Questie.db.char.questAnnounceObjectives` to "on" if not set at all yet
- prevent announce of objective progress when `Questie.db.char.questAnnounceObjectives` is "off" or unset
- added new announce option when picking up items that start quests in options UI and i18n
- announce of quest starting items bound to new option `Questie.db.char.questAnnounceItems`
- added DEBUG messages when announce options are toggled in options UI

### CODE REVIEW

File: Localization/Translations/Options/Social.lua [hunk 1]
```diff
@@ -86,6 +86,30 @@ local socialOptionsLocales = {
...
+        ["ptBR"] = false,
+        ["ruRU"] = false,
+        ["deDE"] = "Quests startende Gegenstände",
+        ["koKR"] = false,
+        ["esMX"] = false,
+        ["enUS"] = true,
+        ["zhCN"] = false,
+        ["zhTW"] = false,
+        ["esES"] = false,
+        ["frFR"] = false,
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:99]:
```suggestion
        ["frFR"] = "Objets commençant une quête",
```

File: Localization/Translations/Options/Social.lua [hunk 2]
```diff
@@ -86,6 +86,30 @@ local socialOptionsLocales = {
...
+        ["ptBR"] = false,
+        ["ruRU"] = false,
+        ["deDE"] = "Teilt das Aufheben von Gegenständen, die eine Quests beginnen, anderen Spielern mit.",
+        ["koKR"] = false,
+        ["esMX"] = false,
+        ["enUS"] = true,
+        ["zhCN"] = false,
+        ["zhTW"] = false,
+        ["esES"] = false,
+        ["frFR"] = false,
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:111]:
```suggestion
        ["frFR"] = "Annonce le ramassage d’objets commençant une quête aux autres joueurs",
```

File: Localization/Translations/Options/Social.lua [hunk 3]
```diff
@@ -86,6 +86,30 @@ local socialOptionsLocales = {
         ["esES"] = nil,
         ["frFR"] = "Types de mises à jour à annoncer dans le chat",
     },
+    ["Items starting a quest"] = {
+        ["ptBR"] = false,
+        ["ruRU"] = false,
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:91]:
```suggestion
        ["ruRU"] = "Предметы, начинающие задание",
```

File: Localization/Translations/Options/Social.lua [hunk 4]
```diff
@@ -86,6 +86,30 @@ local socialOptionsLocales = {
...
+        ["esMX"] = false,
+        ["enUS"] = true,
+        ["zhCN"] = false,
+        ["zhTW"] = false,
+        ["esES"] = false,
+        ["frFR"] = false,
+    },
+    ["Announce looted items that start a quest to other players"] = {
+        ["ptBR"] = false,
+        ["ruRU"] = false,
```
Comment (BreakBB) [inline Localization/Translations/Options/Social.lua:103]:
```suggestion
        ["ruRU"] = "Оповещение о предметах, начинающих задание",
```

**Review by BreakBB — CHANGES_REQUESTED** [review]
The translation team added some of the translations of the new settings.

**Review by BreakBB — APPROVED** [review]
