### PR TITLE
[quest] Fix 'Seize the Ambassador' triggerEnd

### LINKED ISSUE #6104: Missing objective data for quest 26118 - Seize the Ambassador (Ironforge, Cataclysm Classic)
## Description

Hi folks! While running through Dun Morogh quests, I got one from Ironforge Airfield that took me to the Great Seat to talk to the Dark Iron Ambassador. After turning in that quest, we get Seize the Ambassador, which Questie is missing objective data for:

[ERROR] Missing objective data for quest 26118 Arrest Ambassador Slaghammer and bring him to the High Seat

## Wowhead link

https://www.wowhead.com/cata/quest=26118/seize-the-ambassador

## Screenshots

Questie Error:
image

Quest Description:
image

## Questie & WoW version

Questie 10.3.3
WoW 4.4.0 (Cataclysm Classic)

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #6104

## Proposed changes

- Add a fix to include `triggerEnd` for 'Seize the Ambassador' as done in 'Goggle Boggle' & 'Death from Below'.

### CODE REVIEW

File: Database/Corrections/cataQuestFixes.lua [hunk 1]
```diff
@@ -3675,6 +3675,9 @@ function CataQuestFixes.Load()
         [26116] = { -- Kinelory Strikes
             [questKeys.triggerEnd] = {"Protect Kinelory", {[zoneIDs.ARATHI_HIGHLANDS] = {{54.85,55.55}}}},
         },
+        [26118] = { -- Seize the Ambassador
+            [questKeys.triggerEnd] = {"Arrest Ambassador Slaghammer and bring him to the High Seat", {[zoneIDs.IRONFORGE] = {{39.65,56.85}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:3679]: This is correct. However an `extraObjective` pointing to "Ambassador Slaghammer" would be even better. So not only the target position is shown by Questie.

**Review by BreakBB — CHANGES_REQUESTED** [review]

File: Database/Corrections/cataQuestFixes.lua (hunk 1 above)
Comment (Sommos) [reply Database/Corrections/cataQuestFixes.lua]: 47632

File: Database/Corrections/cataQuestFixes.lua [hunk 2]
```diff
@@ -3675,6 +3675,9 @@ function CataQuestFixes.Load()
         [26116] = { -- Kinelory Strikes
             [questKeys.triggerEnd] = {"Protect Kinelory", {[zoneIDs.ARATHI_HIGHLANDS] = {{54.85,55.55}}}},
         },
+        [26118] = { -- Seize the Ambassador
+            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_MOUNT_UP,l10n("Arrest Ambassador Slaghammer and bring him to the High Seat"),0,{{"monster",42146}}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:3679]: Now we lost the first part 😅 

```suggestion
            [questKeys.triggerEnd] = {"Arrest Ambassador Slaghammer and bring him to the High Seat", {[zoneIDs.IRONFORGE] = {{39.65,56.85}}}},
            [questKeys.extraObjectives] = {{nil,Questie.ICON_TYPE_MOUNT_UP,l10n("Arrest Ambassador Slaghammer"),0,{{"monster",42146}}}},
```

We also need to add `"Arrest Ambassador Slaghammer"` to the translations, so we can potentially translate it.

Comment (Sommos) [reply Database/Corrections/cataQuestFixes.lua]: https://github.com/Questie/Questie/pull/6218/commits/e78030d3fc36378f5e5a3abbfed7383fc393f7aa
