### PR TITLE
[quest] Fix 'Deep Impact' Objectives

### LINKED ISSUE #6169: Quest Issue for quest 14268 - Deep Impact (Desolace, Cataclysm Classic)
## Description
This quest requires finding Ancient Tablet Fragment in some ruins in the water and to combine them into one piece. Questie does not indicate where these fragments can be found on the map/minimap. Wowhead indicates the locations on the quest page.

edit: I'd like to note that Wowhead indicates this quest as horde, but I did it as Alliance. I couldn't find a seperate Alliance version of the quest on wowhead.

## Wowhead link
Quest: https://www.wowhead.com/cata/quest=14268/deep-impact
Specific item: https://www.wowhead.com/cata/item=49102/ancient-tablet-fragment

## Questie & WoW version
Questie v10.3.5 & Cataclysm Classic

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #6169

## Proposed changes

- Add a fix to `objectives` for the 'Deep Impact' quest.

### CODE REVIEW

File: Database/Corrections/cataQuestFixes.lua [hunk 1]
```diff
@@ -1583,6 +1583,9 @@ function CataQuestFixes.Load()
         [14267] = { -- Investigating the Sea Shrine
             [questKeys.preQuestSingle] = {14258},
         },
+        [14268] = { -- Deep Impact
+            [questKeys.objectives] = {nil,{{195659,nil,Questie.ICON_TYPE_INTERACT}}},
```
Comment (BreakBB) [inline Database/Corrections/cataQuestFixes.lua:1587]: This is not the way to fix this, as the actual objective is still of type "item". We are using the `requiredSourceItems` table to fix this and add https://www.wowhead.com/cata/item=49102/ancient-tablet-fragment there. Leaving the objective as it is.

**Review by BreakBB — CHANGES_REQUESTED** [review]

File: Database/Corrections/cataQuestFixes.lua (hunk 1 above)
Comment (Sommos) [reply Database/Corrections/cataQuestFixes.lua]: https://github.com/Questie/Questie/pull/6217/commits/edd7b7f4269db10c7994e24d340c3d9ac8a646ba

**Review by BreakBB — APPROVED** [review]
