### PR TITLE
[npc] ADDED: Proper Coordinates For Kazragore When In Horde Base To NPCDB

### LINKED ISSUE #5547: [npc] 'Kazragore' Coordinates Incorrect In NPC DB
## Description

The NPC to hand in the thing in Ashenvale once per week for Horde for the drum has the map icon in the wrong spot in Splintertree. The NPC is inside the Inn, at the back, but the icon shows outside past the mailbox

## Wowhead link

https://www.wowhead.com/classic/npc=217706/kazragore

## Screenshots

N/a

## Questie & WoW version

v9.2.17
WoW Classic SoD - v1.15.052409

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #5547

## Proposed changes

- ADDED: Proper Coordinates For Kazragore When In Horde Base To NPCDB

### CODE REVIEW

File: Database/Corrections/sodNPCFixes.lua [hunk 1]
```diff
@@ -363,7 +363,7 @@ function SeasonOfDiscovery:LoadNPCs()
         },
         [212969] = { -- Kazragore
             [npcKeys.spawns] = {
-                [zoneIDs.ASHENVALE] = {{39.4, 67.2},{73.8,61.9}},
+                [zoneIDs.ASHENVALE] = {{39.4, 67.2},{74.0,60.6}},
```
Comment (BreakBB) [inline Database/Corrections/sodNPCFixes.lua:366]:
```suggestion
                [zoneIDs.ASHENVALE] = {{39.4, 67.2}},
```

**Comment by BreakBB** [comment]
For these kind of "minor" changes/cleanup, we use the `[db]` commit prefix.
