### PR TITLE
[quest] ADDED: Gnomeregan SoD P2 Quests To QuestDB

### LINKED ISSUE #5663: [quest] P2 SoD Gnomeregan Quests Missing From QuestDB
## Description

The P2 SoD quests for Gnomeregan are not currently in the QuestDB. 

## Questie Debug Reports

Quest in dialog not present in QuestDB!

Quest ID: 80137
Quest Name: Save Techbot's Brain!
Quest Text: When our beloved city Gnomeregan fell, a rogue spark must have jolted my poor creation, Techbot.  It once aided me and my associates with its countless gizmos and limitless store of information, but its positronic brain has polarized.  Now it's negatronic... and Techbot's behaviors are reversed.  It roams Gnomeregan in a frenzy!

But perhaps it can be salvaged.  Perhaps, if you can retrieve Techbot's memory core and bring it to me, I can discover the cause of the polarization and fix my poor Techbot.

Objective Text: Bring Techbot's Memory Core to Tinkmaster Overspark in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7944-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.959, 50.147)
QuestLog: 1053, 1701, 4581, 1791, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80180
Quest Name: The Grand Betrayal
Quest Text: I trusted Thermaplugg, human. Never did I expect that he would betray me and the entire gnomish people. And for what? Power? Wealth? All things that he would have had in time. Now we have been displaced from our home and that madman is in charge. The king of nothing....

We will retake Gnomeregan, <playername>. We will not stop until the city is back in our control. If you wish to join in our fight, a simple task I ask of you: Kill the betrayer. Destroy Mekgineer Thermaplugg.
Objective Text: Venture to Gnomeregan and kill Mekgineer Thermaplugg. Return to High Tinker Mekkatorque when the task is complete.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7937-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.090, 49.055)
QuestLog: 1053, 1701, 4581, 1791, 80137, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80143
Quest Name: Data Rescue
Quest Text: When we fled Gnomeregan, we left so much data behind!  Vitally important data!

I need the data on a prismatic punch card, from a Matrix Punchograph 3005-D high security terminal, deep in Gnomeregan.  You must access the terminal, but to do that you first need clearance... and to get that you must access lower security terminals-- models -A, -B and -C.  And to do THAT you need security punch cards, starting with white... and we left all the punch cards in the city.

It's a catastrophe!  Can you help?
Objective Text: Bring a Prismatic Punch Card to Master Mechanic Castpipe in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-7950-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (69.727, 48.626)
QuestLog: 4581, 80137, 1701, 1053, 1791, 80180, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

Quest in dialog not present in QuestDB!

Quest ID: 80136
Quest Name: Essential Artificials
Quest Text: A nigh-universal mechanical component--the essential artificial--was of great use to the tinkers and smiths of Gnomeregan.  But during the frantic exodus from our city, no one remembered to take any of these devices with them!  And I need a large supply of them for work I will soon undertake.

Please, go into Gnomeregan and get me some essential artificials.  You'll find them in the deeper areas of our city, held in containers called artificial extrapolators.

Thank you, <playername>, and please hurry!
Objective Text: Bring 12 Essential Artificials to Klockmort Spannerspan in Ironforge.
Reward Text: 
Reward XP: 0
Questgiver: Creature-0-5253-0-20340-6169-0000467E8E
Character: Lvl 40 HUMAN WARRIOR
Player Coords:  [1455]  (68.552, 46.000)
QuestLog: 4581, 80137, 1701, 1053, 1791, 80180, 80143, 7905, 
Client: 1.15.1 SoD
Questie: v9.3.6
Locale: enUS

## Screenshots

N/a

## Questie & WoW version

v9.3.6
WoW Classic SoD - v1.15.1.53247

### PR DESCRIPTION
**Pull request by Sommos**
## Issue references

Fixes #5663

## Proposed changes

- ADDED: Updated SoD P2 Gnomeregan quests to QuestDB

### CODE REVIEW

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 1]
```diff
@@ -1666,6 +1732,237 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+        },
+        [80157] = {
+            [questKeys.name] = "The Sparklematic 5200!",
+            [questKeys.startedBy] = nil,
+            [questKeys.finishedBy] = nil,
+            [questKeys.requiredLevel] = 40,
+            [questKeys.questLevel] = 40,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.NONE,
+            [questKeys.objectivesText] = {"As quickly as it started, the Sparklematic 5200 comes to an abrupt halt. &nbsp;A simple "ding" is heard from the machine, and the mouth of the machine spirals upward. &nbsp;Inside the Sparklematic 5200 is a small box wrapped in a little bow. &nbsp;The machine would appear to wrap an object up after eliminating its grime-encrusted status. &nbsp;Even if the machine didn't work, at least the item is now wrapped in a pretty box.Well, there is one way to find out if it cleaned the item or not..."},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:1897]: This breaks the code atm.

The `"ding"` ends the string and rips everything apart. Questie doesn't even start ingame and the pipeline also points towards this.

```suggestion
            [questKeys.objectivesText] = {"As quickly as it started, the Sparklematic 5200 comes to an abrupt halt. &nbsp;A simple \"ding\" is heard from the machine, and the mouth of the machine spirals upward. &nbsp;Inside the Sparklematic 5200 is a small box wrapped in a little bow. &nbsp;The machine would appear to wrap an object up after eliminating its grime-encrusted status. &nbsp;Even if the machine didn't work, at least the item is now wrapped in a pretty box.Well, there is one way to find out if it cleaned the item or not..."},
```

We need to cover this case in the crawler though.

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 2]
```diff
@@ -1666,6 +1732,237 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+        },
+        [80161] = {
+            [questKeys.name] = "The Sparklematic 5200!",
+            [questKeys.startedBy] = nil,
+            [questKeys.finishedBy] = nil,
+            [questKeys.requiredLevel] = 40,
+            [questKeys.questLevel] = 40,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.NONE,
+            [questKeys.objectivesText] = {"As quickly as it started, the Sparklematic 5200 comes to an abrupt halt. &nbsp;A simple "ding" is heard from the machine, and the mouth of the machine spirals upward. &nbsp;Inside the Sparklematic 5200 is a small box wrapped in a little bow. &nbsp;The machine would appear to wrap an object up after eliminating its grime-encrusted status. &nbsp;Even if the machine didn't work, at least the item is now wrapped in a pretty box.Well, there is one way to find out if it cleaned the item or not..."},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:1930]:
```suggestion
            [questKeys.objectivesText] = {"As quickly as it started, the Sparklematic 5200 comes to an abrupt halt. &nbsp;A simple \"ding\" is heard from the machine, and the mouth of the machine spirals upward. &nbsp;Inside the Sparklematic 5200 is a small box wrapped in a little bow. &nbsp;The machine would appear to wrap an object up after eliminating its grime-encrusted status. &nbsp;Even if the machine didn't work, at least the item is now wrapped in a pretty box.Well, there is one way to find out if it cleaned the item or not..."},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 3]
```diff
@@ -811,15 +840,124 @@ function SeasonOfDiscovery:LoadQuests()
...
+            [questKeys.zoneOrSort] = zoneIDs.GNOMEREGAN,
+            [questKeys.questFlags] = questFlags.RAID,
+        },
+        [80160] = { -- The Sparklematic 5200!
+            [questKeys.zoneOrSort] = zoneIDs.GNOMEREGAN,
+            [questKeys.questFlags] = questFlags.RAID,
+        },
+        [80180] = { -- The Grand Betrayal
+            [questKeys.finishedBy] = {{7937}},
+            [questKeys.objectives] = {{218537}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:924]:
```suggestion
            [questKeys.objectives] = {{{218537}}},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 4]
```diff
@@ -811,15 +840,124 @@ function SeasonOfDiscovery:LoadQuests()
...
         },
-        [80309] = {
+        [80309] = { -- A Full Shipment
             [questKeys.specialFlags] = specialFlags.REPEATABLE,
         },
+        [80324] = { -- The Mad King
+            [questKeys.startedBy] = {{7937}},
+            [questKeys.finishedBy] = {{7937}},
+            [questKeys.requiredRaces] = raceIDs.ALL_ALLIANCE,
+            [questKeys.objectives] = {nil,nil,{217350}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:949]:
```suggestion
            [questKeys.objectives] = {nil,nil,{{217350}}},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 5]
```diff
@@ -811,15 +840,124 @@ function SeasonOfDiscovery:LoadQuests()
...
+            [questKeys.zoneOrSort] = zoneIDs.GNOMEREGAN,
+            [questKeys.questFlags] = questFlags.RAID,
+        },
+        [80325] = { -- The Mad King
+            [questKeys.startedBy] = {{3412}},
+            [questKeys.finishedBy] = {{3412}},
+            [questKeys.requiredRaces] = raceIDs.ALL_HORDE,
+            [questKeys.objectives] = {nil,nil,{217351}},
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:957]:
```suggestion
            [questKeys.objectives] = {nil,nil,{{217351}}},
```

**Review by BreakBB — CHANGES_REQUESTED** [review]

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 6]
```diff
@@ -1589,6 +1589,28 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+        },
+        [79705] = {
+            [questKeys.name] = "Salvaging the Salvagematic",
+            [questKeys.startedBy] = {{217689}},
+            [questKeys.finishedBy] = nil,
+            [questKeys.requiredLevel] = 40,
+            [questKeys.questLevel] = 40,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.NONE,
+            [questKeys.objectivesText] = {"Bring Ziri "The Wrench" 10 Mithril Bars, 5 Greater Mystic Essence, 3 GG12-082 Cartridge Fuses, and a Pristine G-7 C.O.R.E. Processor and she can get the Salvagematic 9000! working for you. Probably. Maybe."},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:1611]:
```suggestion
            [questKeys.objectivesText] = {"Bring Ziri \"The Wrench\" 10 Mithril Bars, 5 Greater Mystic Essence, 3 GG12-082 Cartridge Fuses, and a Pristine G-7 C.O.R.E. Processor and she can get the Salvagematic 9000! working for you. Probably. Maybe."},
```

File: Database/Corrections/sodQuestFixes.lua [hunk 7]
```diff
@@ -811,15 +840,124 @@ function SeasonOfDiscovery:LoadQuests()
...
+        },
+        [80158] = { -- The Sparklematic 5200!
+            [questKeys.zoneOrSort] = zoneIDs.GNOMEREGAN,
+            [questKeys.questFlags] = questFlags.RAID,
+        },
+        [80160] = { -- More Sparklematic Action
+            [questKeys.zoneOrSort] = zoneIDs.GNOMEREGAN,
+            [questKeys.questFlags] = questFlags.RAID,
+        },
+        [80160] = { -- The Sparklematic 5200!
```
Comment (BreakBB) [inline Database/Corrections/sodQuestFixes.lua:918]:
```suggestion
        [80161] = { -- The Sparklematic 5200!
```

**Review by BreakBB — CHANGES_REQUESTED** [review]

File: Database/Corrections/Automatic/sodBaseQuests.lua [hunk 8]
```diff
@@ -1633,6 +1655,50 @@ function SeasonOfDiscovery:LoadBaseQuests()
...
+        },
+        [79984] = {
+            [questKeys.name] = "Quadrangulation",
+            [questKeys.startedBy] = nil,
+            [questKeys.finishedBy] = nil,
+            [questKeys.requiredLevel] = 40,
+            [questKeys.questLevel] = 40,
+            [questKeys.requiredRaces] = raceIDs.NONE,
+            [questKeys.requiredClasses] = classIDs.NONE,
+            [questKeys.objectivesText] = {"Find Wirdal Wondergear's Quadrangulation Beacons and attune with them. There are four of them and they are located somewhere in Kalimdor. Rewards ."},
```
Comment (BreakBB) [inline Database/Corrections/Automatic/sodBaseQuests.lua:1677]:
```suggestion
            [questKeys.objectivesText] = {"Find Wirdal Wondergear's Quadrangulation Beacons and attune with them. There are four of them and they are located somewhere in Kalimdor."},
```

**Review by BreakBB — APPROVED** [review]
